### ISSUE TITLE
tornadofx.DefaultErrorHandler uncaughtException SEVERE: Uncaught error java.lang.InstantiationException

### ISSUE THREAD

**Issue by vffuunnyy** [edvin/tornadofx#1018]
jdk1.8.0_131
```
июн 25, 2019 4:38:38 AM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:410)
	at tornadofx.FXKt.find$default(FX.kt:399)
	at tornadofx.App.start(App.kt:78)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
```
![image](https://user-images.githubusercontent.com/28656590/60076415-b537f800-9751-11e9-8f57-54179554e886.png)

**Comment by aleksandar-stefanovic** [comment]
I think you'd have more luck on StackOverflow, since the "Issues" section of this repository is related to the bugs in the library code itself, and not the user code.

**Comment by ctadlock** [comment]
Closing as off topic
