### ISSUE TITLE
Cant build tornadofx app via gradle ci

### ISSUE THREAD

**Issue by AlbRoehm** [edvin/tornadofx#1029]
Hey, i'm struggling to setup a build pipeline with gradle for a tornadofx app and somehow cant get the openjfx parts right in the dockerfile 

What i already tried: 
Setup everything with this dockerfile:
`FROM openjdk:8-jdk
RUN apt-get update && apt-get install -y --no-install-recommends openjfx && rm -rf /var/lib/apt/lists/*`

Set it up with this dockerfile
`FROM openjdk:8-jdk
RUN apt-get update && apt-get install openjfx=8u141-b14-3~deb9u1 libopenjfx-java=8u141-b14-3~deb9u1 libopenjfx-jni=8u141-b14-3~deb9u1 -y --no-install-recommends && rm -rf /var/lib/apt/lists/*`

Which both resulted in javafx components not being found.

Use JDK 11 and openjfx-gradle-plugin: 
Resulting in this error:

`
...
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
	... 47 more
Caused by: java.lang.IllegalAccessError: class tornadofx.AsyncKt (in unnamed module @0x7d8fbb97) cannot access class com.sun.glass.ui.Application (in module javafx.graphics) because module javafx.graphics does not export com.sun.glass.ui to unnamed module @0x7d8fbb97
	at tornadofx.AsyncKt.success(Async.kt:115)
	at tornadofx.Component.ui(Component.kt:240)
	at de.drdiestel.views.splitView.SplitView.<init>(SplitView.kt:24)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
...
`

I would really appreciate if you could give me a hand on this and maybe enlarge your guide a little bit in this direction.

**Comment by abhinayagarwal** [comment]
Hi,

TornadoFX still doesn't support JDK 11. There is a branch which is JDK10+ compatible. There are snapshot releases for the same: https://oss.sonatype.org/content/repositories/snapshots/no/tornado/tornadofx/2.0.0-SNAPSHOT/

Please try them in your application and let us know if you face any issue.
