### ISSUE TITLE
UnsatisfiedLinkError When Slider Uses Tick Labels

### ISSUE THREAD

**Issue by snorhax** [edvin/tornadofx#1038]
Like the title says, I get an error only when I set tick labels to show. It used work but I don't know when it stopped working, as I'm working on a massive project and hadn't checked my fragment using sliders in a while. I'm using JDK 11.0.2 and TornadoFX version 1.7.19 but it had worked before with those versions. The only thing I think could have caused the change was the recent upgrade of my IDE, Intellij Community 2019.2

Test Class:
```
import tornadofx.*

fun main(args: Array<String>) {
    launch<TestClass>(args)
}

class TestClass : App (TestView::class)
```
View:
```
import tornadofx.*

class TestView : View("My View") {
       override val root = vbox {
        slider {
            min = 0.0
            max = 100.0
            value = 0.0
            majorTickUnit = 25.0
            minorTickCount = 4
            isShowTickMarks = true
            isShowTickLabels = true //<-------
        }
    }
}
```
Console Readout:
```
Jul 26, 2019 10:50:31 AM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically
java.lang.UnsatisfiedLinkError: com.sun.javafx.font.directwrite.OS.CoInitializeEx(I)Z
	at com.sun.javafx.font.directwrite.OS.CoInitializeEx(Native Method)
	at com.sun.javafx.font.directwrite.DWFactory.getWICFactory(DWFactory.java:127)
	at com.sun.javafx.font.directwrite.DWGlyph.createBitmap(DWGlyph.java:287)
	at com.sun.javafx.font.directwrite.DWGlyph.getCachedBitmap(DWGlyph.java:274)
	at com.sun.javafx.font.directwrite.DWGlyph.getD2DMask(DWGlyph.java:168)
	at com.sun.javafx.font.directwrite.DWGlyph.getPixelData(DWGlyph.java:353)
	at com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:258)
	at com.sun.prism.impl.GlyphCache.render(GlyphCache.java:148)
	at com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2101)
	at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
	at com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
	at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
	at com.sun.javafx.sg.prism.NGNode.renderOpacity(NGNode.java:2336)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2060)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The error then repeats over and over again. Please let me know if this issue can be replicated on your end.

**Comment by edvin** [comment]
TornadoFX 1 is only compatible with Java 8. In any case, it seems like you're hitting a bug in JavaFX itself, not TornadoFX.

**Comment by snorhax** [comment]
Thanks for pointing that out, I've changed to the 2.0.0-SNAPSHOT. And I think you're right about it being a JavaFX problem, although it's still frustrating since I haven't changed JavaFX versions recently.  Thanks anyways.

**Comment by edvin** [comment]
Great! Please report any issues you find with 2.0.0-SNAPSHOT. I've started to port a major app myself to 2.0, so we'll get an official release in a matter of months I hope.
