### ISSUE TITLE
replaceWith BUG

### ISSUE THREAD

**Issue by jrfeng** [edvin/tornadofx#1077]
**Exception :**

```txt
java.lang.RuntimeException: Exception in Application stop method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:922)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: root.scene must not be null
	at tornadofx.UIComponent.unInit(Component.kt:575)
	at tornadofx.App.stop(App.kt:140)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:882)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more
```

**Reproduce BUG**：call `UIComponent#replaceWith` method, then closed window will cause this exception. but, if i back to the original View and closed window will not cause this exception.

**This is my code :**

```kotlin
import javafx.geometry.Pos
import tornadofx.*

fun main(args: Array<String>) {
    launch<TestApp>(args)
}


class TestApp : App(MyView::class)

class MyView : View("MyView") {
    override val root = stackpane {
        minWidth = 360.0
        minHeight = 240.0

        button("Click Me") {
            action {
                replaceWith(MyOtherView::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
            }
        }
    }
}

class MyOtherView : View("MyOtherView") {
    override val root = vbox {
        minWidth = 200.0
        minHeight = 160.0
        alignment = Pos.CENTER
        spacing = 8.0

        label("This is other View")
        button("Back") {
            action {
                replaceWith(MyView::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.RIGHT))
            }
        }
    }
}
```

**Comment by edvin** [comment]
Not sure I understand how to trigger this issue with your code sample?

**Comment by jrfeng** [comment]
I saw the latest source code, this BUG is fixed, sorry.

**Comment by avanwouwe** [comment]
Hi jrfeng. Can you let me know what you saw? I seem to be getting the same issue when the application is shut down. I am on  1.7.19

At app.stop() tornadofx determines the primary view with determinePrimaryView(), and four lines further performs an unInit() on it. However, determinePrimaryView() finds the LoginView class that defined in the App, and that one no longer as a root.scene, ever since I called replaceWith() to show the real MainView. This then results in the "root.scene must not be null". 

I just do not understand why this is not happening in the tornadofx-sample case, where I lifted the code?

**Comment by jrfeng** [comment]
@avanwouwe this bug is fixed  ([click me](https://github.com/edvin/tornadofx/blob/6211a3fdf1bca255cd5948f3b7ae3360746cda3a/src/main/java/tornadofx/Component.kt#L579)), but not release yet. mabe you can built it yourself.
