### ISSUE TITLE
Making editable tableview throws InaccessibleObjectException

### ISSUE THREAD

**Issue by natekfl** [edvin/tornadofx#1079]
Making the tableview:
```kotlin
tableview(observableListOf(ReadySensor("Test"))) {
    isEditable = true

    readonlyColumn("Name", ReadySensor::name)
    column("Ready", ReadySensor::readyProperty)
    column("Bypassed", ReadySensor::bypassedProperty).makeEditable()
}
```

The ReadySensor data class:
```kotlin
class ReadySensor(val name: String) {
    val readyProperty = SimpleBooleanProperty(false)
    var ready by readyProperty

    val bypassedProperty = SimpleBooleanProperty(false)
    var bypassed by bypassedProperty

}
```

The error:
```
SEVERE: Uncaught error
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @6141af49
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:341)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at tornadofx.FXKt.getChildrenReflectively(FX.kt:680)
	at tornadofx.FXKt.getChildList(FX.kt:671)
	at tornadofx.FXKt.addChildIfPossible(FX.kt:609)
	at tornadofx.FXKt.addChildIfPossible$default(FX.kt:498)
	at tornadofx.ControlsKt.checkbox(Controls.kt:870)
	at tornadofx.ControlsKt.checkbox$default(Controls.kt:159)
	at tornadofx.ItemControlsKt$useCheckbox$$inlined$apply$lambda$1$1.invoke(ItemControls.kt:472)
	at tornadofx.ItemControlsKt$useCheckbox$$inlined$apply$lambda$1$1.invoke(ItemControls.kt)
	at tornadofx.NodesKt.cache(Nodes.kt:1283)
	at tornadofx.NodesKt.cache$default(Nodes.kt:1282)
	at tornadofx.ItemControlsKt$useCheckbox$$inlined$apply$lambda$1.invoke(ItemControls.kt:470)
	at tornadofx.ItemControlsKt$useCheckbox$$inlined$apply$lambda$1.invoke(ItemControls.kt)
	at tornadofx.SmartTableCell.updateItem(TableView.kt:100)
	at javafx.controls/javafx.scene.control.TableCell.updateItem(TableCell.java:665)
	at javafx.controls/javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls/javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:119)
	at javafx.controls/javafx.scene.control.skin.TableSkinUtils.resizeColumnToFitContent(TableSkinUtils.java:86)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(TableColumnHeader.java:589)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.updateScene(TableColumnHeader.java:532)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.lambda$new$0(TableColumnHeader.java:159)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1125)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1163)
	at javafx.graphics/javafx.scene.Parent$2.onChanged(Parent.java:371)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.updateContent(NestedTableColumnHeader.java:578)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.updateTableColumnHeaders(NestedTableColumnHeader.java:504)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.checkState(NestedTableColumnHeader.java:638)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.computePrefHeight(NestedTableColumnHeader.java:345)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1033)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.controls/javafx.scene.control.skin.TableHeaderRow.computePrefHeight(TableHeaderRow.java:402)
	at javafx.controls/javafx.scene.control.skin.TableHeaderRow.computeMinHeight(TableHeaderRow.java:395)
	at javafx.graphics/javafx.scene.Parent.minHeight(Parent.java:1061)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.controls/javafx.scene.control.SkinBase.computeMinHeight(SkinBase.java:311)
	at javafx.controls/javafx.scene.control.Control.computeMinHeight(Control.java:512)
	at javafx.graphics/javafx.scene.Parent.minHeight(Parent.java:1061)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Region.java:1525)
	at javafx.graphics/javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.graphics/javafx.scene.layout.BorderPane.getAreaHeight(BorderPane.java:631)
	at javafx.graphics/javafx.scene.layout.BorderPane.computePrefHeight(BorderPane.java:481)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1039)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.graphics/javafx.scene.Scene.getPreferredHeight(Scene.java:1811)
	at javafx.graphics/javafx.scene.Scene.resizeRootToPreferredSize(Scene.java:1780)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1747)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at tornadofx.App.start(App.kt:101)
	at ride.SystemApp.start(SystemApp.kt:15)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Note that this error only ocurrs with the addition of `makeEditable()`. Without that call, the table renders fine, though of course it is not editable as is desired.

**Comment by edvin** [comment]
Sounds like you're trying to use TornadoFX 1 with something other than Java 8 :) For J9+ you can try your app against the 2.0.0-SNAPSHOT release which is available in oss.sonatype.org.

**Comment by viniciusccarvalho** [comment]
I was able to fix this by adding `--add-opens=javafx.graphics/javafx.scene=tornadofx` to the jvm arguments of the application. See https://github.com/controlsfx/controlsfx/issues/1166 for similar issue.

It's hard to believe that java module system is as painful as OSGi was 12 years ago, and nothing changed.
