### ISSUE TITLE
jdk10 / datagrid throws IllegalAccessException

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#1101]
running KPhoto using oracle jdk11 and tornadofx 2.0.0-SNAPSHOT throws IllegalAccessException during startup:
/usr/lib/jvm/java-11-oracle/bin/java --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED -javaagent:/home/ron/idea-IU-192.5728.98/lib/idea_rt.jar=35743:/home/ron/idea-IU-192.5728.98/bin -Dfile.encoding=UTF-8 -classpath /home/ron/src/KPhoto/target/classes:/home/ron/.m2/repository/no/tornado/tornadofx/2.0.0-SNAPSHOT/tornadofx-2.0.0-SNAPSHOT.jar:/home/ron/.m2/repository/org/glassfish/javax.json/1.1.2/javax.json-1.1.2.jar:/home/ron/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.41/kotlin-stdlib-jdk8-1.3.41.jar:/home/ron/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.41/kotlin-stdlib-jdk7-1.3.41.jar:/home/ron/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.3.41/kotlin-reflect-1.3.41.jar:/home/ron/.m2/repository/de/jensd/fontawesomefx-fontawesome/4.7.0-9.1.2/fontawesomefx-fontawesome-4.7.0-9.1.2.jar:/home/ron/.m2/repository/de/jensd/fontawesomefx-commons/9.1.2/fontawesomefx-commons-9.1.2.jar:/home/ron/.m2/repository/org/openjfx/javafx-controls/11/javafx-controls-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-controls/11/javafx-controls-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-fxml/11/javafx-fxml-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-fxml/11/javafx-fxml-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-swing/11/javafx-swing-11.jar:/home/ron/.m2/repository/org/openjfx/javafx-swing/11/javafx-swing-11-linux.jar:/home/ron/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.50/kotlin-stdlib-1.3.50.jar:/home/ron/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50/kotlin-stdlib-common-1.3.50.jar:/home/ron/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/home/ron/.m2/repository/net/coobird/thumbnailator/0.4.8/thumbnailator-0.4.8.jar:/home/ron/.m2/repository/com/drewnoakes/metadata-extractor/2.10.0/metadata-extractor-2.10.0.jar:/home/ron/.m2/repository/com/adobe/xmp/xmpcore/5.1.3/xmpcore-5.1.3.jar:/home/ron/.m2/repository/javax/json/javax.json-api/1.1.2/javax.json-api-1.1.2.jar:/home/ron/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar -p /home/ron/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-linux.jar:/home/ron/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11-linux.jar nl.codetribe.MyApp
Oct 19, 2019 10:02:38 PM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically
Exception in Application start method
Exception in Application stop method
Oct 19, 2019 10:02:38 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x49062cc6) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x49062cc6
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javafx.scene.control.Control.<clinit>(Control.java:86)
	at tornadofx.ControlsKt.menubar(Controls.kt:375)
	at nl.codetribe.view.TopView$root$1.invoke(TopView.kt:26)
	at nl.codetribe.view.TopView$root$1.invoke(TopView.kt:17)
	at tornadofx.LayoutsKt.hbox(Layouts.kt:429)
	at tornadofx.LayoutsKt.hbox$default(Layouts.kt:137)
	at nl.codetribe.view.TopView.<init>(TopView.kt:25)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at tornadofx.FXKt.find(FX.kt:437)
	at tornadofx.FXKt.find$default(FX.kt:426)
	at tornadofx.UIComponent.plusAssign(Component.kt:903)
	at nl.codetribe.view.MainView$root$1$1.invoke(MainView.kt:13)
	at nl.codetribe.view.MainView$root$1$1.invoke(MainView.kt:10)
	at tornadofx.LayoutsKt.region(Layouts.kt:181)
	at tornadofx.LayoutsKt.top(Layouts.kt:174)
	at nl.codetribe.view.MainView$root$1.invoke(MainView.kt:13)
	at nl.codetribe.view.MainView$root$1.invoke(MainView.kt:10)
	at tornadofx.LayoutsKt.borderpane(Layouts.kt:465)
	at nl.codetribe.view.MainView.<init>(MainView.kt:12)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at tornadofx.FXKt.find(FX.kt:437)
	at tornadofx.FXKt.find$default(FX.kt:426)
	at tornadofx.App.start(App.kt:83)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more

Process finished with exit code 1

**Comment by ctadlock** [comment]
Closing due to inactivity; reopen if its still an issue.
