### ISSUE TITLE
How I avoid ConcurrentModificationException?

### ISSUE THREAD

**Issue by thapld** [edvin/tornadofx#1113]
I play with ConcurrentModificationException error in version 1.7.19:

```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[na:1.8.0_211]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[na:1.8.0_211]
	at tornadofx.EventBus$fire$1.invoke(EventBus.kt:126) ~[tornadofx-1.7.19.jar:na]
	at tornadofx.EventBus$fire$3.run(EventBus.kt:117) ~[tornadofx-1.7.19.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_211]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177) [jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]
```

How I avoid the ConcurrentModificationException?

**Comment by edvin** [comment]
I believe this has already been addressed. Can you try with 1.7.20-SNAPSHOT? If you're still having the same issue, please post a minimal code sample we can use to reproduce the error.

**Comment by thapld** [comment]
Thank you for your support. I did change to snapshot version and it's okie.
