### ISSUE TITLE
JsonModel cannot convert to double value from json data

### ISSUE THREAD

**Issue by saqi7022** [edvin/tornadofx#1206]
Here is my model class

```
class SampleModel(id: Long = 0L, name:String="", amount:Double=0.0 ) 
{
    val idProperty = SimpleLongProperty(id)

    var id:Long? by idProperty

    val nameProperty = SimpleStringProperty(name)

    var name by nameProperty

    val amountProperty = SimpleDoubleProperty(amount)

    var amount by amountProperty
}
```

i am getting this error

```
java.lang.ClassCastException: org.glassfish.json.JsonStringImpl cannot be cast to javax.json.JsonNumber
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonNumber(JsonObjectBuilderImpl.java:247)
	at tornadofx.JsonKt$jsonNumber$1.invoke(Json.kt:126)
	at tornadofx.JsonKt$jsonNumber$1.invoke(Json.kt)
	at tornadofx.JsonKt.firstNonNull(Json.kt:118)
	at tornadofx.JsonKt.jsonNumber(Json.kt:126)
	at tornadofx.JsonKt.double(Json.kt:123)
	at tornadofx.JsonKt.getDouble(Json.kt:124)
	at com.example.demo.models.settings.FeeStructure.updateModel(SampleModel.kt:54)
	at com.example.demo.controllers.settings.FeeStructureController.findAll(SampleModelController.kt:44)
	at com.example.demo.view.settings.FeeStructureView$onRefresh$1.invoke(SampleModelsView.kt:59)
	at com.example.demo.view.settings.FeeStructureView$onRefresh$1.invoke(SampleModelsView.kt:13)
	at tornadofx.NodesKt$asyncItems$5.invoke(Nodes.kt:466)
	at tornadofx.NodesKt$asyncItems$5.invoke(Nodes.kt)
	at tornadofx.FXTask.call(Async.kt:457)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

i am targeting this data

```
[
 {
    "id": 2,
    "created_at": "2020-04-01T13:07:39.289536Z",
    "updated_at": "2020-04-01T13:25:02.439203Z",
    "status": true,
    "name": "General Structure",
    "amount": "2000.00",
   }
]
```

What i am doing wrong?

**Comment by ruckustboom** [comment]
Your amount is a String in your JSON. It should be

```json
...
"amount": 2000.0,
...
```

**Comment by saqi7022** [comment]
:) Thank you i didnt even notice that.... solved the issue
