### ISSUE TITLE
TreeView error when using autocommit with extractors

### ISSUE THREAD

**Issue by SKeeneCode** [edvin/tornadofx#1208]
I'm hitting an error that is simply beyond my ability to debug, although I have narrowed it down and [created a minimal example](https://gist.github.com/SKeeneCode/0ec1466a2ed547761e7294dd3cdd7020) that reproduces the problem. I am praying someone smarter and more educated than me can help me out.

To reproduce the the 'bug' (or my error), expand the tree, click on any tree item that isn't a group, then click on a group and try and edit it below. It throws the error:

> SEVERE: Uncaught error
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.sak33.wiki.app.MyItemModel.setGroup, parameter <set-?>
	at com.sak33.wiki.app.MyItemModel.setGroup(MinimalExample.kt)
	at com.sak33.wiki.app.MyItemViewModel$group$1.set(MinimalExample.kt:29)
	at tornadofx.PropertiesKt$observable$1.set(Properties.kt:68) (and so on...)

It will not throw this error if you edit the groups before clicking anything else, although it will bug again if you then click a nongroup tree item and try to edit another group.

Removing `autocommit = true` from `MyGroupViewModel` will prevent the bug, but of course changed are not commuting and not reflected in the treeview.

Removing `autocommit = true` from `MyItemViewModel` will prevent the bug, but then when the user changed the group of an item, it will not be reflected in the treeview.

This only started happening when I started using extractors to fire update events for the treeview to organize itself. Something about the `autocommit = true` in `MyItemViewModel` and `MyGroupViewModel` are conflicting. My guess in the dark is it must be something to do with the update events that are fired from using extractors, because before I had no extractors and was using a very ugly set of listeners for each property and did not have this problem.

**Comment by SchweinchenFuntik** [comment]
j`ava.lang.IllegalArgumentException: Parameter specified as non-null is null: method` - you apply null somewhere where notnull is expected

look at these code fragments (I think the problem may be in them):
```
if (it?.value is MyGroupModel) { // MyItemModel
    item = it.value as MyGroupModel // casting type is bad
}
```
`itemViewModel.rebindOnChange(this.selectionModel.selectedItemProperty())` - binds your properties when nothing is selected there null, and you declared the model as notnull

**Comment by SKeeneCode** [comment]
> j`ava.lang.IllegalArgumentException: Parameter specified as non-null is null: method` - you apply null somewhere where notnull is expected
> 
> look at these code fragments (I think the problem may be in them):
> 
> ```
> if (it?.value is MyGroupModel) { // MyItemModel
>     item = it.value as MyGroupModel // casting type is bad
> }
> ```
> 
> `itemViewModel.rebindOnChange(this.selectionModel.selectedItemProperty())` - binds your properties when nothing is selected there null, and you declared the model as notnull

My understanding was that the `it?.value` is an appropriate null check. I might be wrong but even if I do an explicit check for null here (in both):

```
                    itemViewModel.rebindOnChange(this.selectionModel.selectedItemProperty()) {
                        if (selectionModel.selectedItem == null) return@rebindOnChange
                        val selectedItem = selectionModel.selectedItem.value
                        if (selectedItem is MyItemModel) {
                           println("rebind item " + selectedItem)
                            item = selectedItem
                        }
                    }
```

I still get the same error. The `println` verifies for me that the viewmodels only have their items changed when the user selects a item treecell or a group tree cell. 

I added in some print outs on keypress:

```
setOnKeyPressed { event ->
                if (event.code == KeyCode.A) {
                        println(itemViewModel.item.name)
                        println(groupViewModel.item.name)
                }
            }
```

And at no point do I see anything unusual. It's worth nothing if you haven't run the example yourself that despite the error being thrown, the edit is correctly made and the treeView correctly updates. If I remember the code fragments you referenced have remained the same from before I used extractors and ran error free.

**Comment by SKeeneCode** [comment]
Okay by changing the print out to:

```
setOnKeyPressed { event ->
                    if (event.code == KeyCode.CONTROL) {
                        println("item is ${itemViewModel.name} with group ${itemViewModel.group}")
                        println("item is ${groupViewModel.name}")
                    }
                }
```

I found a lead. It looks like while the SimpleStringProperty is being change correctly, the group property isn't and remains pointing to the default group the ItemModel is initialized with.

**Comment by SKeeneCode** [comment]
So I fixed it by fluke but I don't understand how it fixed it:

If I remove `var group: MyGroupModel by groupProperty` from `MyItemModel` and in `MyItemViewModel` I bind directly to the property with `val group = bind(MyItemModel::groupProperty, autocommit = true)`

And change any reference from `itemViewModel.group` to `itemViewModel.groupProperty.value`

It *somehow* fixes the problem, although after editing an item the selection instantly jumps to the group.

I'm not sure why this fixes it.

**Comment by SchweinchenFuntik** [comment]
probably because your tree is not associated with a list, these are different structures. I already answered a similar question, maybe yours. You need to give ObservableList to populate, also save it a link to it, and listen to the changes in your reference list, and change the secondary tree-like lists, or redraw the tree. It’s also worth going to Slack instead of chatting in git

**Comment by SKeeneCode** [comment]
> It’s also worth going to Slack instead of chatting in git

Sure. I haven't used Slack before but send me an invite link and I'll jump in. I think there's some things I need clarification on.

**Comment by SchweinchenFuntik** [comment]
I can invite, I need mail and your name (how to sign you)

**Comment by ruckustboom** [comment]
You can get an invite to the Kotlin Slack here: [https://surveys.jetbrains.com/s3/kotlin-slack-sign-up](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up). From there, you can join the TornadoFX channel.

**Comment by deggers** [comment]
Wow @SKeeneCode your example solved a problem i had for days! I wasnt able to figure out how to do a prober binding between my tree and its value .. I did some refactoring because you missed some nice extension-function tornadoFX provides. Furthermore your first mentioned error you could avoid by having a validation check before commiting any ill-formed values to your model i think. If you want i will try to make a gist with your code refactored - because the ItemViewModels also do not need to get a Model passed - i think this makes the code all in all cleaner. 

Thank you again very much for showing your code - it helped me a lot!

**Comment by SKeeneCode** [comment]
Hey @deggers 
>  I did some refactoring because you missed some nice extension-function tornadoFX provides.
Would love to see what ones I missed! 

>  Furthermore your first mentioned error you could avoid by having a validation check before commiting any ill-formed values to your model i think. 

In the end I simply removed the property delegates `var name: String by nameProperty` etc. I simply couldn't find where and why I was getting a null so I accepted this refactor instead.

>If you want i will try to make a gist with your code refactored
This would be great, would be nice to see your improvements.

> because the ItemViewModels also do not need to get a Model passed - i think this makes the code all in all cleaner.

This is true, I chose to put in the optional parameter because I am often reading in data from a file and constructing the model object from it. Then I can simply use the view model constructor to supply it with my newly created model.

**Comment by deggers** [comment]
Hey @SKeeneCode 

> Would love to see what ones I missed!

Sure. I am not sure if this behaves like you want it to behave - but you can edit the group now anytime, or i didn't test it properly enough - let me know what you think :) [Gist](https://gist.github.com/deggers/2943c1af62de0abe72c66e9d1ca55583)

Something missing would be adding a validator to the textfield to make sure no incorrect data is autocommited [Guide](https://edvin.gitbooks.io/tornadofx-guide/part1/11_Editing_Models_and_Validation.html)

> This is true, I chose to put in the optional parameter because I am often reading in data from a file and constructing the model object from it. Then I can simply use the view model constructor to supply it with my newly created model.

Sure, makes totally sense! Did not had this in mind :-)
