### ISSUE TITLE
Tornadofx 2.0 TableView, error dirty column 

### ISSUE THREAD

**Issue by SchweinchenFuntik** [edvin/tornadofx#1236]
code:
```
class Model {
    val dateProperty: ObjectProperty<LocalDate> = objectProperty(LocalDate.now())
    var date: LocalDate by dateProperty

    val valueProperty: SimpleObjectProperty<BigDecimal> = SimpleObjectProperty(BigDecimal.ZERO)
    var value: BigDecimal by valueProperty

}

class ErrorDirtyTable : View("My View") {
    val items = observableListOf(Model(), Model())

    override val root = tableview(items) {
        column("Date", Model::dateProperty).makeEditable()
        column("Value", Model::valueProperty).makeEditable()

        enableDirtyTracking() // without this line everything works
    }
}
```
![ErrorDirtyValue](https://user-images.githubusercontent.com/22637705/82193831-9d83d800-98fe-11ea-8383-923ff349c3ec.gif)

```
java.util.ConcurrentModificationException
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator$VetoableIteratorDecorator.checkForComodification(VetoableListDecorator.java:714)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator$VetoableIteratorDecorator.hasNext(VetoableListDecorator.java:682)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at tornadofx.skin.tablerow.DirtyDecoratingTableRowSkin.layoutChildren(DirtyDecoratingTableRowSkin.java:39)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.controls/javafx.scene.control.Cell.layoutChildren(Cell.java:633)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by SchweinchenFuntik** [comment]
I think a similar solution should solve the problem. I'll try at home

```
public final class DirtyDecoratingTableRowSkinNew<T> extends TableRowSkin<T>  {
    // code

protected void layoutChildren(double x, double y, double w, double h) {
        super.layoutChildren(x, y, w, h);
        final ObservableList<Node> src = getChildren();
        final List<Node> children = new ArrayList<>(src.size());
        Collections.copy(children, src);

        children.forEach(child -> {
            TableCell<T, ?> cell = (TableCell<T,?>) child;
            T item = null;
            if (cell.getIndex() > -1 && cell.getTableView().getItems().size() > cell.getIndex()) {
                item = cell.getTableView().getItems().get(cell.getIndex());
            }
            Polygon polygon = getPolygon(cell);
            boolean isDirty = item != null && editModel.getDirtyState(item).isDirtyColumn(cell.getTableColumn());
            if (isDirty) {
                if (!children.contains(polygon)) {
                    src.add(polygon);
                }
                polygon.relocate(cell.getLayoutX(), y);
            } else {
                src.remove(polygon);
            }
        });
    }
}
```

**Comment by AdelDima** [comment]
This commit should go on TornadoFX 2, I have tested it and it works, thanks @SchweinchenFuntik  for your solution.
