### ISSUE TITLE
InaccessibleObjectException: Unable to make protected ObservableList javafx.scene.Parent.getChildren() accessible

### ISSUE THREAD

**Issue by utybo** [edvin/tornadofx#1270]
### Versions

* Compiling for Java 11
* JavaFX 11.0.2, Kotlin 1.4.0
* Using the 2.0-SNAPSHOT
* JDK 14 from AdoptOpenJDK

### Sample

```kotlin
data class Person(val name: String, val department: String)

val persons = listOf(
    Person("Mary Hanes","Marketing"),
    Person("Steve Folley","Customer Service"),
    Person("John Ramsy","IT Help Desk"),
    Person("Erlick Foyes","Customer Service"),
    Person("Erin James","Marketing"),
    Person("Jacob Mays","IT Help Desk"),
    Person("Larry Cable","Customer Service")
)

val departments = persons
    .map { it.department }
    .distinct().map { Person(it, "") }

class FolderView : View() { // line 41
    override val root = treeview<Person> {
        root = TreeItem(Person("Departments", ""))
        cellFormat { ite ->
            graphic = cache { // line 45
                hbox { label("Test") } // line 46
            }
        }
        populate { parent ->
            if (parent == root) departments else persons.filter { it.department == parent.value.name }
        }
    }

}
```

### Exception

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @6815dce3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:349)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:289)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
	at tornadofx.FXKt.getChildrenReflectively(FX.kt:684)
	at tornadofx.FXKt.getChildList(FX.kt:675)
	at tornadofx.FXKt.addChildIfPossible(FX.kt:613)
	at tornadofx.FXKt.addChildIfPossible$default(FX.kt:499)
	at tornadofx.LayoutsKt.hbox(Layouts.kt:428)
	at tornadofx.LayoutsKt.hbox$default(Layouts.kt:137)
	at guru.zoroark.dratini.FolderView$root$1$1$1.invoke(FolderView.kt:46)
	at guru.zoroark.dratini.FolderView$root$1$1$1.invoke(FolderView.kt:41)
	at tornadofx.NodesKt.cache(Nodes.kt:1286)
	at tornadofx.NodesKt.cache$default(Nodes.kt:1285)
	at guru.zoroark.dratini.FolderView$root$1$1.invoke(FolderView.kt:45)
	at guru.zoroark.dratini.FolderView$root$1$1.invoke(FolderView.kt:41)
	at tornadofx.SmartTreeCell.updateItem(TreeView.kt:90)
	at javafx.controls/javafx.scene.control.TreeCell.updateItem(TreeCell.java:523)
	at javafx.controls/javafx.scene.control.TreeCell.indexChanged(TreeCell.java:481)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1742)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1726)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1852)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2755)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1245)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1206)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1748)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at tornadofx.App.start(App.kt:102)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### Probable cause

I don't know why, but I only encounter it in this *specific case*, where I'm trying to add formatting to a tree's cell.

https://github.com/edvin/tornadofx/blob/01b83cde456eeddcc7f356d4f6a0549feb226bc5/src/main/java/tornadofx/FX.kt#L680-L688

The main problem is the `isAccessible` change, which is prohibited in new JDK versions due to accessing restricted fields. The main question being, why is that reflection code being called in the first place?...

### Workaround

Add the following to your `application { }` block in your `build.gradle`:

```
applicationDefaultJvmArgs = ['--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED']
```

**Comment by SchweinchenFuntik** [comment]
it is described here: https://github.com/edvin/tornadofx/tree/jdk10#tornadofx-and-jdk-9

**Comment by utybo** [comment]
The example given in the readme is different from mine and the `--add-opens` is also different @SchweinchenFuntik

**Comment by SchweinchenFuntik** [comment]
as an experiment, try kotlin 1.3.72, it seemed to me that there were no problems before

**Comment by utybo** [comment]
Same error happens with Kotlin 1.3.72

**Comment by SchweinchenFuntik** [comment]
I have not reproduced:
<ul>
   <li> JavaFX 11.0.2, Kotlin 1.4.0
    <li> TornadoFX 2.0-SNAPSHOT
    <li> JDK: 11, 14  Liberica FX;  14 Adopt HotSpot, J9
</ul>

**Comment by SchweinchenFuntik** [comment]
>
    Compiling for Java 11
    JavaFX 11.0.2, Kotlin 1.4.0
    Using the 2.0-SNAPSHOT
    JDK 14 from AdoptOpenJDK

I saw that you are using different JDK for java and JavaFX.  Сombine versions and unsubscribe

**Comment by pavlus** [comment]
Same as of #1217

**Comment by utybo** [comment]
That's great news, thanks for the info!

**Comment by SchweinchenFuntik** [comment]
@pavlus thanks, it's strange that I didn't notice when I merged the branches. I didn't have any errors, like many, the tests passed. Perhaps it depends on the JDK version.

I will try to do a PR as soon as possible, maybe it's worth it right away in  https://github.com/edvin/tornadofx2

**Comment by praveenray** [comment]
Any thoughts on pushing this as a release to maven central (instead of snapshot).
I'm behind a corp proxy which is restrictive in what repositories are allowed.

**Comment by wittlock** [comment]
I would also really like to see this fix in a proper release to maven central. I'm also stuck behind a corporate proxy that won't let me get artefacts from other repositories.
