### ISSUE TITLE
Resource must not be null exceptions occurs when generated jar file is run.When I run the project , it totally fine.I use fxml for resources.

### ISSUE THREAD

**Issue by Leo-Thura** [edvin/tornadofx#1273]

**Comment by SchweinchenFuntik** [comment]
describe in more detail namely:
<ul>
   <li> a simple example where the error is reproduced;
   <li> specify the project build system;
   <li> project structure if it differs from the standard
</ul>

**Comment by Leo-Thura** [comment]
java.lang.IllegalStateException: component.javaClass.getResource(resource) must not be null
	at tornadofx.ResourceLookup.url(Component.kt:1304)
	at tornadofx.FX$Companion$fxmlLocator$1.invoke(FX.kt:114)
	at tornadofx.FX$Companion$fxmlLocator$1.invoke(FX.kt:88)
	at tornadofx.UIComponent.loadFXML(Component.kt:1119)
	at tornadofx.UIComponent$fxml$1.<init>(Component.kt:1113)
	at tornadofx.UIComponent.fxml(Component.kt:1112)
	at tornadofx.UIComponent.fxml$default(Component.kt:1112)
	at view.MainView.<init>(MainView.kt:21)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at tornadofx.FXKt.find(FX.kt:434)
	at tornadofx.FXKt.find$default(FX.kt:423)
	at tornadofx.App.start(App.kt:83)
	at main.MyApp.start(MyApp.kt:54)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)


**I use gradle build system**

`class AppLauncher {

    companion object {

        @JvmStatic
        fun main(args : Array<String>) {

            MyApp().main(arrayOf())
        }

    }
}`
I also use this app launcher class the MyApp application

**Comment by SchweinchenFuntik** [comment]
> MyApp().main(arrayOf())

incorrect launch
https://edvin.gitbooks.io/tornadofx-guide/content/part1/3_Components.html
```
// 
fun main(args: Array<String>) {
  launch<MyApp>(args) // start app JavaFX (TornadoFX)
}
```

**Comment by SchweinchenFuntik** [comment]
very similar to https://github.com/edvin/tornadofx/issues/1268

what version of `TornadoFX` and `JavaFX` do you have?

**Comment by Leo-Thura** [comment]
Tornadofx : 1.7.20 and Javafx : 11.0.2

**Comment by SchweinchenFuntik** [comment]
answer above, you need "TornadoFX 2.0-SNAPSHOT"

**Comment by Leo-Thura** [comment]
I tried Snapshot version . I still get the same error when I run the generated jar file.

**Comment by SchweinchenFuntik** [comment]
Have you changed the application launch?

**Comment by SchweinchenFuntik** [comment]
also make sure you are using the correct version

**Comment by Leo-Thura** [comment]
Yes . I changed the application launch.

**Comment by Leo-Thura** [comment]
I'm currently using JDK 11 . Do I need to change to higher JDK.

**Comment by Leo-Thura** [comment]
`
class TestView : View("My View") {

    override val root : Parent = FXMLLoader.load(javaClass.getResource("/TestView.fxml"))
}`

**When I load fxml with FXMLLOADER , I get new error :-) **
tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.NullPointerException: Location is required.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3230)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3194)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3163)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3136)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3113)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3106)
	at main.TestView.<init>(TestView.kt:9)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at tornadofx.FXKt.find(FX.kt:434)
	at tornadofx.FXKt.find$default(FX.kt:423)
	at tornadofx.App.start(App.kt:83)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by SchweinchenFuntik** [comment]
I'll try to throw off an example project tomorrow

**Comment by Leo-Thura** [comment]
Finally I found a solution . May not be a good solution . But it works for me.

`
class TestView : View("My View") {

    private val url = File("src/main/resources/TestView.fxml").toURI().toURL()
    override val root: Parent =  FXMLLoader(url).also { loader -> loader.setController(this) }.load()

    @FXML
    lateinit var lbl_test : Label

    init {

        lbl_test.text = "This is testing string"
    }
}`

**Comment by SchweinchenFuntik** [comment]
here is an example project [TornadoFX simple.zip](https://github.com/edvin/tornadofx/files/5214107/TornadoFX.simple.zip)
