### ISSUE TITLE
Cannot run application

### ISSUE THREAD

**Issue by yandroidUA** [edvin/tornadofx#1288]
Exception:
```
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
	at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Screen.getNativeScreen()" because "<parameter1>" is null
	at com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
	at com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:738)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:279)
	at com.sun.glass.ui.Application.lambda$run$1(Application.java:153)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)

```
Code:
```

import javafx.scene.text.FontWeight
import tornadofx.*

class HelloWorldApp : App(HelloWorld::class, Styles::class) {
    init {

    }
}

class Styles : Stylesheet() {
    init {
        label {
            fontSize = 20.px
            fontWeight = FontWeight.BOLD
            backgroundColor += c("#cecece")
        }
    }
}

class HelloWorld : View() {
    override val root = hbox {
        label("Hello world")
    }
}

fun main(args: Array<String>) {
    launch<HelloWorldApp>()
}

```
Gradle:
```

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm")
    application
    id("com.github.johnrengelman.shadow") version "5.0.0"
    id("org.openjfx.javafxplugin") version "0.0.9"
}

group = "com.github.yandroidua"
version = "0.0.1"

repositories {
    mavenCentral()
}

application {
    mainClassName = "lab3.LauncherKt"
}

javafx {
    version = "12"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.web", "javafx.graphics")
}

dependencies {
    val coroutinesVersion: String by project
    val tornadoFxVersion: String by project
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
    implementation("no.tornado:tornadofx:$tornadoFxVersion")
}

tasks.withType<Jar> {
    manifest {
        attributes(
                mapOf(
                        "Main-Class" to application.mainClassName
                )
        )
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

kotlin.sourceSets["main"].kotlin.srcDirs("src")
kotlin.sourceSets["test"].kotlin.srcDirs("test")

sourceSets["main"].resources.srcDirs("resources")
sourceSets["test"].resources.srcDirs("testresources")
```

**Comment by SchweinchenFuntik** [comment]
version tornadofx ? Using tornadofx 2 (java 9+)

**Comment by yandroidUA** [comment]
No, I'm using `1.7.20`.
How to add 2.0 using gradle?
Trying to ` implementation("no.tornado:tornadofx:2.0") ` - not working

**Comment by yandroidUA** [comment]
Using:
```
repositories {
    mavenCentral()
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}

```
and this:
```
implementation("no.tornado:tornadofx:2.0.0-SNAPSHOT")
```

And everything works fine, thx
