### ISSUE TITLE
java.lang.Object cannot be cast to class tornadofx.JsonModel

### ISSUE THREAD

**Issue by glothos** [edvin/tornadofx#1302]
I'm facing this issue while trying to process response of Rest. Funny thing is that this is only happening in my Windows 10 machine and it doesn't happen in my OS X.

```
java.lang.ClassCastException: class java.lang.Object cannot be cast to class tornadofx.JsonModel (java.lang.Object is in module java.base of loader 'bootstrap'; tornadofx.JsonModel is in unnamed module of loader 'app')
	at io.karmaddress.controllers.ApiController.processResponse(ApiController.kt:27)
	at io.karmaddress.controllers.LoginController$loginAction$1.invoke(LoginController.kt:26)
	at io.karmaddress.controllers.LoginController$loginAction$1.invoke(LoginController.kt:11)
	at tornadofx.FXTask.call(Async.kt:465)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This is the function:
```
class ApiController: Controller() {
    fun <T>processResponse(response: Rest.Response): T {
        try {
            if (response.ok()) {
                val status = response.one().getJsonString("status").toString()
                val message = response.one().getJsonString("message").toString()
                if (status == "error") {
                    fire(FailureEvent(message))
                    throw Exception(message)
                } else {
                    return response.one().getJsonObject("data").toModel()
                }
            }
            else {
                throw Exception("Internal Server Error")
            }
        } finally {
            response.consume()
        }
    }
}
```

this is the function that calls it:

```
private fun loginAction(credentials: JsonObject) {
        runAsync {
            fire(AuthRequesting())
            val request = api.post("auth/login", credentials)
            apiController.processResponse<AuthResponse>(request)
        } success {
            with(authModel.config) {
                set(authModel.KEY_TOKEN_INFO to it.accessToken)
                set(authModel.KEY_USER_ID to it.user.id)
                save()
                fire(AuthSuccess())
            }
        }
    }
```

and this is the model

```
class AuthResponse: JsonModel {
    val accessTokenProperty = SimpleStringProperty(this, "accessToken")
    var accessToken by accessTokenProperty

    val channelKeyProperty = SimpleStringProperty()
    var channelKey by channelKeyProperty

    val typeProperty = SimpleStringProperty()
    var type by typeProperty

    val userProperty = SimpleObjectProperty<User>()
    var user by userProperty

    override fun updateModel(json: JsonObject) {
        with(json) {
            accessToken = string("accessToken")
            channelKey = string("channelKey")
            type = string("type")
            user = getJsonObject("user")?.toModel()
        }
    }

    override fun toJSON(json: JsonBuilder) {
        with(json) {
            add("accessToken", accessToken)
            add("channelKey", channelKey)
            add("type", type)
            add("user", user?.toJSON())
        }
    }
}
```

I'm using version 2.0.0-SNAPSHOT. By the way, great framework. Love it!

**Comment by glothos** [comment]
In the end it was a language error.

`processResponse` function worked when I did it like so:

```
inline fun <reified A: JsonModel> processResponse(response: Rest.Response): A {
        try {
            if (response.ok()) {
                val status = response.one().getJsonString("status").toString()
                val message = response.one().getJsonString("message").toString()
                if (status == "error") {
                    fire(FailureEvent(message))
                    throw Exception(message)
                } else {
                    return response.one().getJsonObject("data").toModel()
                }
            }
            else {
                throw Exception("Internal Server Error")
            }
        } finally {
            response.consume()
        }
    }
```
