### ISSUE TITLE
Can't call the Stage.init?() methods

### ISSUE THREAD

**Issue by Finnerale** [edvin/tornadofx#164]
This
```java
class MyApp: App(MainView::class, Styles::class) {
    override fun start(stage: Stage) {
        super.start(stage)
        stage.initStyle(StageStyle.UNDECORATED)
    }
}
```
causes this exception:
```
Exception in Application start method
Aug 26, 2016 12:23:46 PM tornadofx.DefaultErrorHandler uncaughtException
SCHWERWIEGEND: Uncaught error
java.lang.NoSuchMethodException: de.leopoldluley.exacalc.app.MyApp.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)
```
How can I make the Stage undecorated / modal / a child stage?

**Comment by edvin** [comment]
Move `stage.initStyle(StageStyle.UNDECORATED)` before `super.start(stage)`. You can't change the stage style after the stage has been shown, so this makes sure you do it before :)
