### ISSUE TITLE
Importing CSS files within stylesheets.

### ISSUE THREAD

**Issue by dant3** [edvin/tornadofx#202]
Hi,

I'm using a javafx library which provides css files I need to import in order for it's components to be rendered correctly. How can I do it with tornadofx? I didn't found any mentions of it.
My first guess was to try and import it in my custom `Stylesheet`, but there was no relevant function for it.

I made a poor's man solution to serve myself, but It might be a nice addition to the library:
```
class MyStyle : Stylesheet() {
    val cssImports = listOf(
            "/resources/css/main-font.css",
            "/resources/css/main-style.css"
    )

    override fun render(): String =
        cssImports.map { "@import \"${javaClass.getResource(it)}\"" }.joinToString("\n") +
                "\n" + super.render()
}
```

**Comment by edvin** [comment]
It looks like we currently only support imports of type safe stylesheets. They can be added in the constructor of your stylesheet. I'll defer to @t-boom to provide a good solution to this, but in the mean time you should be able to just do `importStylesheet("/resources/css/main-font.css")` within the `init` block of your `App` class.

**Comment by t-boom** [comment]
I'll look into this and see if I can come up with a good solution.

**Comment by dant3** [comment]
Not exactly really, since I would love to have inheritance between my custom stylesheet and unsafe one supplier with library, so it only loaded if needed.

**Comment by edvin** [comment]
Then you can load the unsafe stylesheet in the init block of the companion object of the typesafe stylesheet :)

**Comment by dant3** [comment]
Unfortunately doing so makes application crash with stacktrace like:

```
java.lang.NoClassDefFoundError: Could not initialize class myapplication.MyStylesheet
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sun.net.www.protocol.css.Handler$CSSURLConnection.getInputStream(Handler.kt:20)
	at java.net.URL.openStream(URL.java:1045)
	at com.sun.javafx.css.parser.CSSParser.parse(CSSParser.java:244)
	at com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(StyleManager.java:1079)
	at com.sun.javafx.css.StyleManager.loadStylesheet(StyleManager.java:910)
	at com.sun.javafx.css.StyleManager.processStylesheets(StyleManager.java:1531)
	at com.sun.javafx.css.StyleManager.gatherSceneStylesheets(StyleManager.java:1600)
	at com.sun.javafx.css.StyleManager.findMatchingStyles(StyleManager.java:1638)
	at javafx.scene.CssStyleHelper.createStyleHelper(CssStyleHelper.java:111)
	at javafx.scene.Node.reapplyCss(Node.java:8983)
	at javafx.scene.Node.impl_processCSS(Node.java:9180)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1249)
	at javafx.scene.Node.processCSS(Node.java:9056)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
```

I believe this is due to classloader loop, since to get resource address I'm using reference to some javaClass.

**Comment by edvin** [comment]
I just tested this in one of my apps with no issues. You should be able to get to your resource without referencing any class, just supply the full path inside the classpath:

```kotlin
class Styles : Stylesheet() {
    companion object {
        importStylesheet("/resources/css/main-font.css")    
        importStylesheet("/resources/css/main-style.css")    
    }
}
```

**Comment by edvin** [comment]
I think this is a good enough solution for now, so I'll close the issue. It can be reopened if somebody wants to work on a specific feature for this.
