### ISSUE TITLE
How to bind datagrid's selectedItem??

### ISSUE THREAD

**Issue by codehz** [edvin/tornadofx#224]
```Kotlin
import javafx.application.Application
import javafx.scene.Parent
import tornadofx.*

class TestData : JsonModel {
    var data: String by property()
    fun dataProperty() = getProperty(TestData::data)

    override fun toJSON(json: JsonBuilder) {
        super.toJSON(json)
        with(json) {
            add("data", data)
        }
    }
}

class TestViewModel(val td: TestData = TestData()) : ViewModel() {
    val data = bind { td.dataProperty() }
}

class TestView : View() {
    val tvm: TestViewModel by inject()

    override val root = form {
        fieldset("Input") {
            field("data") {
                datagrid(listOf("A", "B", "C").observable()) {
                    tvm.data.bind(selectionModel.selectedItemProperty())
                }
            }
            buttonbar {
                button("Submit") {
                    setOnAction {
                        tvm.commit {
                            println("BOOM")
                        }
                    }
                }
            }
        }
    }
}

class Launcher : App() {
    override val primaryView = TestView::class
}

fun main(args: Array<String>) {
    Application.launch(Launcher::class.java, *args)
}
```

it throw a runtime exception: 
```
SEVERE: Uncaught error
java.lang.RuntimeException: TestViewModel. : A bound value cannot be set.
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:140)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at TestViewModel$$special$$inlined$bind$1.changed(ViewModel.kt:96)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
	at tornadofx.ViewModel$commit$1.invoke(ViewModel.kt:150)
	at tornadofx.ViewModel$commit$1.invoke(ViewModel.kt:24)
	at tornadofx.FX$Companion.runAndWait(FX.kt:137)
	at tornadofx.ViewModel.commit(ViewModel.kt:145)
	at tornadofx.ViewModel.commit$default(ViewModel.kt:142)
	at TestView$root$1$1$2$1$1.handle(Test.kt:34)
	at TestView$root$1$1$2$1$1.handle(Test.kt:21)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by edvin** [comment]
The reason you can't bind bidirectionally towards the selectedItem, is that the grid wants to update this property as the the selection changes. Bidirectional binding prevents this, hence the error.

If you want your model property to update whenever the selection changes you can do a unidirectional binding towards the selectedItem property instead:

```kotlin
selectionModel.selectedItemProperty().bind(tvm.data)
```

If you want external changes to the data model to update the selection in the grid you will have to use a listener to update the selection.

Did that answer your question?

**Comment by edvin** [comment]
I'm sorry for this, it is due to a bug in the framework. I've submitted a fix for the issue now, along with a convenience function to bind towards the selected item of a datagrid. If you can upgrade to `1.5.10-SNAPSHOT` (you need to build it locally and install) your code will run unchanged. You can then also simplyfy the binding statement like this:

```kotlin
bindSelected(tvm.data)
```

(Instead of `tvm.data.bind(selectionModel.selectedItemProperty())`)

If upgrading to 1.5.10-SNAPSHOT is not an option, you can work around the issue by using a listener to set the model value instead of a binding:

```kotlin
selectionModel.selectedItemProperty().onChange { 
    tvm.data.value = it
}
```

Instructions for building the snapshot version locally:

```bash
git clone https://github.com/edvin/tornadofx
mvn install
```
Is this sufficient for you? I'm very sorry for the inconvenience.

**Comment by codehz** [comment]
This is a good solution.
It's a good idea to keep this issue open until the new release

**Comment by edvin** [comment]
1.6.0 has been released :)
