### ISSUE TITLE
Uncaught error when switch slide(fast then the animation)

### ISSUE THREAD

**Issue by codehz** [edvin/tornadofx#225]
Detail: 
```
SEVERE: Uncaught error
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method tornadofx.NodesKt.replaceWith, parameter $receiver
	at tornadofx.NodesKt.replaceWith(Nodes.kt)
	at tornadofx.NodesKt.replaceWith$default(Nodes.kt:917)
	at tornadofx.Slideshow.goto(Slideshow.kt:85)
	at tornadofx.Slideshow.next(Slideshow.kt:42)
	at tornadofx.Slideshow$hookNavigationShortcuts$1$1.handle(Slideshow.kt:61)
	at tornadofx.Slideshow$hookNavigationShortcuts$1$1.handle(Slideshow.kt:16)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:216)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:148)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:247)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:246)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

I think the event handler should be disabled while transition is in progress...

**Comment by edvin** [comment]
That sounds reasonable. @t-boom do you agree that this is the way to solve it? I suspect you might have some thoughts on this :)

**Comment by t-boom** [comment]
Does this only happen when transitioning the root or will it happen when transitioning any node?

**Comment by t-boom** [comment]
It seems like disabling the event handler when any node is transitioning could cause issues, but I definitely see the reasoning for disabling when transitioning the root.

**Comment by edvin** [comment]
This turned out to be a bug in `Slideshow` and has nothing to do with your eminent transitions @t-boom :) Sorry about that! I have committed a fix for the issue now.

**Comment by t-boom** [comment]
"Eminent" might be a bit of an exaggeration, but I'm glad you got it fixed.
