### ISSUE TITLE
Non-null parameter being called with null value from tornadofx code

### ISSUE THREAD

**Issue by CAD97** [edvin/tornadofx#271]
[`Forms.kt:244`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Forms.kt#L244) can run `text.isNotBlank()` while `text: String!` is `null`.

<details><summary><strong>Stack Trace</strong></summary><pre>
SEVERE: Uncaught error
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.text.StringsKt__StringsJVMKt.isBlank, parameter $receiver
	at kotlin.text.StringsKt__StringsJVMKt.isBlank(StringsJVM.kt)
	at tornadofx.AbstractField.computePrefHeight(Forms.kt:244)
	at tornadofx.AbstractField.computeMinHeight(Forms.kt:272)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:436)
	at javafx.scene.layout.VBox.computeContentHeight(VBox.java:518)
	at javafx.scene.layout.VBox.computeMinHeight(VBox.java:396)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
	at javafx.scene.layout.VBox.getAreaHeights(VBox.java:436)
	at javafx.scene.layout.VBox.computeContentHeight(VBox.java:518)
	at javafx.scene.layout.VBox.computeMinHeight(VBox.java:396)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
	at javafx.scene.layout.BorderPane.getAreaHeight(BorderPane.java:618)
	at javafx.scene.layout.BorderPane.computeMinHeight(BorderPane.java:415)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.boundedNodeSizeWithBias(Region.java:1917)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2323)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2238)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2179)
	at javafx.scene.layout.StackPane.layoutChildren(StackPane.java:342)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at tornadofx.App.start(App.kt:68)
	at cad97.anden.tact.TACTApp.start(TACTApp.kt:10)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
</pre></details>
<br />

Walking back how `text` is populated, we see:

- [`var text by property(text)`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Forms.kt#L224). This gives `text` the observed type of `String!` from the `property` delegate.
- [`... AbstractField(text: String? = null, ...`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Forms.kt#L223). This means that our `text` variable defaults to `var text: String! by property<String?>(null)`.

As such, `text` can very clearly hold null, and should be typed as such (`String?`) if that is desired, which then makes clear that the call on line 244 is potentially problematic.

-----

You can see [my project which triggered this here](https://github.com/CAD97/AndensMountain/tree/b5ac8f5f6c1f3ecf51bb4e8b8784f630988e7de9/TextAdventureCreationTool). I don't know what exactly caused the issue to occur, though it did happen while I was transitioning to using FXML, so it's likely something in the FXML loading. Unfortunately, the stack-trace is vague enough that I can't narrow it down further easily. I do think that I have shown that the variable in question can be null, however.

Note that the project in the linked folder requires the sibling project `AdventureDataFormat` (which requires `org.yaml:snakeyaml:1.17`), `no.tornadofx:tornadofx:1.7.0`, and `org.controlsfx:controlsfx:8.40.12`. (I should learn and set up gradle or maven, but that's neither here nor there.)

**Comment by CAD97** [comment]
I take back the what I said about not being able to narrow it down. The error is only produced when using a `Field` without a `text` attribute in FXML. See [this gist for a minimal reproduction case](https://gist.github.com/CAD97/f66c7f1c668168da8965a123ec16369a).

**Comment by edvin** [comment]
As noted on the PR: Thank you for the thorough report and PR. You are completely right, as long as the text property is defined as nullable, we must treat it as such. Great work! I've merged your fix now.
