### ISSUE TITLE
NPE when binding Spinner

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#274]
Hi, playing around with the `spinner` gave me a NullPointerException:

```
java.lang.NullPointerException
	at tornadofx.ItemControlsKt.spinner(ItemControls.kt:43)
	at tornadofx.ItemControlsKt.spinner$default(ItemControls.kt:41)
	at SpinnerTest$root$1.invoke(SpinnerTest.kt:11)
	at SpinnerTest$root$1.invoke(SpinnerTest.kt:6)
	at tornadofx.FXKt.opcr(FX.kt:398)
	at tornadofx.LayoutsKt.borderpane(Layouts.kt:90)
	at SpinnerTest.<init>(SpinnerTest.kt:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:363)
	at tornadofx.FXKt.find$default(FX.kt:349)
	at tornadofx.App.start(App.kt:56)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

```kotlin
class SpinnerTest : View() {

    val prop = SimpleIntegerProperty(1)

    override val root = borderpane {
        center {
            spinner(true, prop)
        }
    }
}
```

**Comment by dominiks** [comment]
Ah, I see. When I use that builder it works.

Works until my next issue: the spinner builder expects a `Property<Int>` or `Property<Double>` but the ViewModel transforms it into a `Property<Number>`. It does work as intendet if I use a `SimpleObjectProperty` instead of a `SimpleIntegerProperty` but is that the correct way to go?

```kotlin
`class TheModel {
    val numberProperty = SimpleIntegerProperty(1)
}

class ViewModel(model: TheModel): ItemViewModel<TheModel>(model) {
    val number = bind { item?.numberProperty }
}

class SpinnerTest : View() {

    val viewModel = ViewModel(TheModel())

    override val root = borderpane {
        center {
            spinner(0, 10, viewModel.number.value, property = viewModel.number)
        }
    }
}
```

**Comment by edvin** [comment]
I've made some adjustments so that the Int/Double spinner builders have defaults for `min`, `max` and `initialValue`. The `initialValue` is taken from the property if supplied, else it is 0 or 0.0.

The first spinner builder you ran into trouble with now requires you to configure a `valueFactory` or it will throw a helpful error message.

Will look at the last issue (Number vs Int) now.

**Comment by edvin** [comment]
I think I found a way to merge the Int/Double spinner builders into one Number build and simultaneously squash the last issue.

**Comment by edvin** [comment]
I've merged the Int/Double spinner builders so you can now write:

```kotlin
spinner(0, 10, property = viewModel.number)
```

The initial value is extracted from the property.

It doesn't matter if you bind against a `Property<Int>`, a `IntegerProperty`, `Property<Double>` or DoubleProperty or any of their sub classes :)
