### ISSUE TITLE
Can't find fxml file

### ISSUE THREAD

**Issue by hiucimon** [edvin/tornadofx#278]
I am trying to get some simple TornatoFX samples working, and I have tried about every iteration of directory locations for my dxml resource, and no matter what, it can never be found. I am in IntelliJ, and currently this is my code...

package sample.org.hiucimon.JavaFX

import javafx.scene.control.Label
import javafx.scene.layout.HBox
import tornadofx.*

class HelloWorld : View() {
    override val root: HBox by fxml("./resources/views/HelloWorld.fxml")
    val label: Label by fxid()
    init {
        label.text = "Hello world"
    }
}

Kotin 1.1.0
TornadoFX 1.7.0

java.lang.IllegalArgumentException: FXML not found for class sample.org.hiucimon.JavaFX.HelloWorld
	at tornadofx.UIComponent$fxml$1.<init>(Component.kt:647)
	at tornadofx.UIComponent.fxml(Component.kt:640)
	at tornadofx.UIComponent.fxml$default(Component.kt:640)
	at sample.org.hiucimon.JavaFX.HelloWorld.<init>(HelloWorld.kt:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:363)
	at tornadofx.FXKt.find$default(FX.kt:349)
	at tornadofx.App.start(App.kt:56)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by edvin** [comment]
If you are using Maven or Gradle, those tools will not copy arbitrary files to your build folder by default. I would recommend putting them in the same folder structure as your package, but in `src/main/resources`. Those files are always copied to the build folder and requires no additional setup.

In your case, create `/src/main/resources/sample/org/hiucimon/JavaFX/HelloWorld.fxml` and you should be able to declare your root node with `override val root: HBox by fxml()`.

Alternatively, you must instruct your build system to copy .fxml files to your build folder.

**Comment by edvin** [comment]
One other tip: You're using a package name of `JavaFX` instead of the lower case `javafx`. Depending on your file system, you may run into trouble with that as well.

**Comment by hiucimon** [comment]
My resources folder is in src/mainresources.

I am using Maven.

I will try it without the explicit filename, but I would like to be able to give specific names.

Not sure how to instruct my build to copy arbitrary file? I have done JavaFX with dxml before and never had this issue.

**Comment by edvin** [comment]
OK, let's go back to your original setup. You write that you declare it as `HBox by fxml("./resources/views/HelloWorld.fxml")`. That would mean that your view is in `src/main/resources/resources/views/HelloWorld.fxml`. I suspect you really have it in `src/main/resources/views/HelloWorld.fxml`, ie. not two folders named `resources` after each other.

Try changing your declaration to `HBox by fxml("/views/HelloWorld.fxml")`.

Also, do a `mvn clean build` and then check where the `HelloWorld.fxml` file is afterwards. That will give you an idea of what went wrong. If this doesn't resolve it, please post your project and I'll have a look.

**Comment by edvin** [comment]
Did you get this working?

**Comment by edvin** [comment]
Closing the issue as this is not a framework bug. But please comment further if you're stilling having issues :)
