### ISSUE TITLE
ClassCastException on Eventbus.subscribe

### ISSUE THREAD

**Issue by arturbosch** [edvin/tornadofx#280]
I noticed that the subscribe methods of eventbus changed a bit since 1.6.2.

When using the eventbus like this:

```kotlin
FX.eventbus.subscribe(event = OpenFileEvent::class, scope = DefaultScope) {
	loadJsonContent(it)
}
```
I get a ClassCastException.

```java
java.lang.ClassCastException: de.unibremen.st.codesmellviewer.VersionsBar$1 cannot be cast to kotlin.jvm.functions.Function2
	at tornadofx.EventBus.subscribe(EventBus.kt:55)
	at tornadofx.EventBus.subscribe$default(EventBus.kt:54)
	at de.unibremen.st.codesmellviewer.VersionsBar.<init>(VersionsBar.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:363)
	at de.unibremen.st.codesmellviewer.ViewerFrame$root$1.invoke(ViewerFrame.kt:25)
	at de.unibremen.st.codesmellviewer.ViewerFrame$root$1.invoke(ViewerFrame.kt:10)
	at tornadofx.FXKt.opcr(FX.kt:398)
	at tornadofx.LayoutsKt.borderpane(Layouts.kt:90)
	at de.unibremen.st.codesmellviewer.ViewerFrame.<init>(ViewerFrame.kt:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:363)
	at tornadofx.FXKt.find$default(FX.kt:349)
	at tornadofx.App.start(App.kt:56)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

Using TornadoFX 1.7 and Kotlin 1.1.0/1.1..
Without any changes 1.6.2 works as expected.

**Comment by edvin** [comment]
That's correct, we introduced the notion of an event executing in an `EventContext`. This change made it possible to call `unsubscribe()` inside the event handler to cancel any further event callbacks. Later we added a `times` parameter to `subscribe` to allow automatic de-registerations after being called the specified number of times.

I'm sorry for the API break, I know it's not good form, but I felt it was better to do it before the `EventBus` had wide spread usage.

**Comment by arturbosch** [comment]
Do you have an example how to use the eventbus now?

**Comment by edvin** [comment]
You code above should be written like:

```kotlin
subscribe<OpenFileEvent> {
    loadJsonContent(it)
}
```

There is no need to mention the default scope if that's what you're using, and provided you're in a view or a controller, you can access it via the available `subscribe` function.

**Comment by arturbosch** [comment]
Ok, thx you that helped :)
