### ISSUE TITLE
[help] JSON configuration settings 

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#297]
I try to use JSON configuration settings.
![image](https://cloud.githubusercontent.com/assets/22107668/24947900/136bccac-1f9b-11e7-8050-208fb7db7c38.png)
But the result is still Propertis file

**Comment by edvin** [comment]
That's correct, the config file itself would be Properties formatted, but it should contain a JSON file which you can get back using `jsonModel("value")`. We are contemplating support for writing the whole file as JSON, but it has not been implemented as of now.

**Comment by QingMings** [comment]
![image](https://cloud.githubusercontent.com/assets/22107668/24948206/283a4dd8-1f9c-11e7-9b5d-d14c92221ecc.png)

**Comment by edvin** [comment]
Which version are you running aginst? I believe this was fixed a little while ago.

**Comment by edvin** [comment]
You can try this snapshot build:

https://oss.sonatype.org/content/repositories/snapshots/no/tornado/tornadofx/

**Comment by QingMings** [comment]
<properties>
        <kotlin.version>1.1.1</kotlin.version>
        <tornadofx.version>1.7.1</tornadofx.version>
    </properties>

**Comment by QingMings** [comment]
kotlin 1.1.1
tornadoFx 1.7.1

**Comment by QingMings** [comment]
there is my model `Solution`
`class Solution() :JsonModel{  `
   `  var name by property<String>()`
   ` fun nameProperty() =getProperty(Solution::name)`
 `   var cameralist =FXCollections.observableArrayList<Camera1>()`
  `  fun cameralistProperty() =getProperty(Solution::cameralist)`

   ` override fun updateModel(json: JsonObject) {`
       ` super.updateModel(json)`
          `  with(json){`
                `name= string("name")`
                `cameralist.setAll(getJsonArray("cameraList").toModel())`
          `  }`
    `}`


`}`

**Comment by edvin** [comment]
It should work with 1.7.2-SNAPSHOT, in the mean time you can circumvent the problem with:

```kotlin
set("value" to solutionController.getModel().toJSON())
```

**Comment by QingMings** [comment]
`Camera1`  


```class Camera1():JsonModel{
    var id by property<String>()
    fun idProperty() = getProperty(Camera1::id)
    var name by property<String>()
    fun nameProperty() =getProperty(Camera1::name)
    var ip by property<String>()
    fun ipProperty() =getProperty(Camera1::ip)

    override fun updateModel(json: JsonObject) {
        super.updateModel(json)
        with(json){
            id=string("id")
            name=string("name")
            ip=string("ip")
        }
    }

}

**Comment by QingMings** [comment]
how to use this snapshot , I use Maven to build，How to configure

**Comment by QingMings** [comment]
I got it! sorry

**Comment by edvin** [comment]
Great! I will add some information about the snapshot builds to the README today.

**Comment by QingMings** [comment]
But still the same
```#
#Wed Apr 12 16:49:59 CST 2017
value=[com.iezview.model.Solution@42752164]

**Comment by edvin** [comment]
You haven't provided a `toJSON(model)` function in `Solution`, so the framework doesn't know how to turn that entity into JSON. That's probably not the problem though, since it should just have generated an empty JSon value (`{}`). You can add `toJSON` while I investigate :) Will get back to you in a little while, I need to fix another issue I'm working on first.

**Comment by edvin** [comment]
I found the error and have committed a fix. I will push a new snapshot to sonatype right away. I tested it with a Customer object which implements JsonModel and did this:

```kotlin
with(config) {
    set("customer" to customer.item)
    save()

    val c: Customer? = jsonModel("customer")
    println(c?.name)
}
```

The config file contained:

```
#
#Wed Apr 12 13:21:55 CEST 2017
customer={"name"\:"Edvin syse"}
```

**Comment by QingMings** [comment]
yes,I used the  new snapshot ,it work fine.
Thanks. :)

**Comment by edvin** [comment]
Great! Thanks for reporting this.

**Comment by QingMings** [comment]
Sorry to ask you again，
I saved JSON successfully
`solutions={"solutionNames"\:[{"name"\:"\u65B9\u6848\u4E00"}]}`
When I reload them，An exception occurred.
```java
java.security.PrivilegedActionException: java.lang.InstantiationException: com.iezview.model.Solutions
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
Caused by: java.lang.InstantiationException: com.iezview.model.Solutions
	at java.lang.Class.newInstance(Class.java:427)
	at com.iezview.controller.SolutionController.testLoadSolu(SolutionController.kt:84)
	at com.iezview.view.TopView$root$1$1$1$1$1.invoke(TopView.kt:18)
	at com.iezview.view.TopView$root$1$1$1$1$1.invoke(TopView.kt:10)
	at tornadofx.MenuKt$menuitem$6$1.handle(Menu.kt:139)
	at tornadofx.MenuKt$menuitem$6$1.handle(Menu.kt)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	... 6 more
Caused by: java.lang.NoSuchMethodException: com.iezview.model.Solutions.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 44 more  

```
  
     

   I try to use the kotlin noarg plugin,But still wrong.
Here are my model and controller:

```java
class Solutions(sn: List<SolutionName>) :JsonModel{

    var solutionNames: ObservableList<SolutionName> = FXCollections.observableArrayList<SolutionName>(sn)
    fun solutionNamesProperty()=getProperty(Solutions::solutionNames)
    override fun updateModel(json: JsonObject) {
        with(json){
            solutionNames.setAll(getJsonArray("solutions").toModel())
        }
    }

    override fun toJSON(json: JsonBuilder) {
        with(json){
            add("solutionNames",solutionNames.toJSON())
        }
    }
}
```
```java
class  SolutionName(solutionName: String) :JsonModel{
     var name by property<String>(solutionName)
    fun nameProperty() =getProperty(SolutionName::name)
    override fun updateModel(json: JsonObject) {
        with(json){
            name=string(name)
        }
    }

    override fun toJSON(json: JsonBuilder) {
        with(json){
            add("name",name)
        }
    }
}
```
Controller method ：
```java
 fun saveSolution(solutionName:String,solution:Solution): Unit {
            with(config){
                set(solutionName to solution)
                save()
                if(config.jsonModel<Solutions>("solutions")==null){
                    set("solutions" to Solutions(listOf(SolutionName(solutionName))))
                    save()
                }else{
                   var solutions= config.jsonModel<Solutions>("solutions")
                    solutions?.solutionNames?.add(SolutionName(solutionName))
                }
            }
    }
```
