### ISSUE TITLE
NPE in layout debugger

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#305]
Clicking the root element in the layout debugger's tree view results in a NPE. This apparently happens since the 1.7.2 release.

```
kotlin.KotlinNullPointerException
	at tornadofx.Fieldset.getForm(Forms.kt:183)
	at tornadofx.AbstractField.computePrefWidth(Forms.kt:273)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at com.sun.javafx.scene.control.skin.ScrollPaneSkin.computeScrollNodeSize(ScrollPaneSkin.java:929)
	at com.sun.javafx.scene.control.skin.ScrollPaneSkin.layoutChildren(ScrollPaneSkin.java:822)
	at javafx.scene.control.Control.layoutChildren(Control.java:578)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by edvin** [comment]
Thank you :) Fixed now.
