### ISSUE TITLE
Error in DefaultErrorHandler

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#328]
```
Mai 19, 2017 11:26:48 AM tornadofx.DefaultErrorHandler uncaughtException
SCHWERWIEGEND: Uncaught error
java.lang.ArrayIndexOutOfBoundsException: 0
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:49)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

tornadoxfx creates an exception while handling some (unknown) Error. This way the original exception isn't visible anymore and only an unhelpful error window is displayed:

![Screenshot](https://cloud.githubusercontent.com/assets/4310707/26241825/6fbe0a58-3c86-11e7-9855-c596b8af3c4c.png)

**Comment by edvin** [comment]
Thanks :) Fixed now.
