### ISSUE TITLE
NullPointerException when using "config" since 1.7.1

### ISSUE THREAD

**Issue by Finnerale** [edvin/tornadofx#335]
In my project I have a settings controller which allows me to access the app's settings from everywhere.
I also use it to store the main window's last position and size which I restore at the top of the App class start method, so it's the first thing that happens.
Everything worked fine until i updated TornadoFX to the newest version, after doing so I got this error when starting the app:
`
Exception in Application start method
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: kotlin.KotlinNullPointerException
	at tornadofx.FX$Companion.getApplication(FX.kt:118)
	at tornadofx.Component.getApp(Component.kt:119)
	at tornadofx.Component.getConfigPath(Component.kt:91)
	at tornadofx.Configurable$DefaultImpls.loadConfig(Component.kt:76)
	at tornadofx.Component.loadConfig(Component.kt:81)
	at tornadofx.Component$config$2.invoke(Component.kt:92)
	at tornadofx.Component$config$2.invoke(Component.kt:81)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at tornadofx.Component.getConfig(Component.kt)
	at de.finnerale.filebase.controller.SettingsCtrl.getHideNameSearch(SettingsCtrl.kt:23)
	at de.finnerale.filebase.controller.SettingsCtrl.<init>(SettingsCtrl.kt:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:365)
	at tornadofx.FXKt.find$default(FX.kt:351)
	at de.finnerale.filebase.app.MyApp$$special$$inlined$inject$1.getValue(App.kt:127)
	at de.finnerale.filebase.app.MyApp$$special$$inlined$inject$1.getValue(App.kt:126)
	at de.finnerale.filebase.app.MyApp.getSettingsCtrl(MyApp.kt)
	at de.finnerale.filebase.app.MyApp.start(MyApp.kt:17)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
`

I've tested which version of TornadoFX causes this and it runns fine on v1.7.0 and breaks on v1.7.1 or newer, so after it's possible to specify the path of the config file.

Thats the structure of my SettingsCtrl:
```
class SettingsCtrl : Controller() {
    fun save() = config.save()

    var windowX: Double
        get() = config.double("window.x") ?: 0.0
        set(value) { config.put("window.x", value.toString()) }

    var windowY: Double
        get() = config.double("window.y") ?: 0.0
        set(value) { config.put("window.y", value.toString()) }

    //more like this
}
```

I've fixed the Issue by adding
`
override val configPath: Path
        get()  = File("settings.properties").absoluteFile.toPath()
`
to my SettingsCtrl but it's important that it is an absoluteFile otherwise it throws a NullPointerException when trying to save it...

**Comment by edvin** [comment]
Hey! I'm not able to reproduce this - can you create a small test that triggers it?

**Comment by Finnerale** [comment]
With TornadoFX 1.7.5 - Kotlin 1.1.2-4 - jvmTarget 1.8
```
class BugCtrl : Controller() {
    var test: Boolean
        get() = config.boolean("test")
        set(value) { config.setProperty("test", value.toString()) }
}

class MyApp: App(MainView::class, Styles::class) {
    val bugCtrl: BugCtrl by inject()

    override fun start(stage: Stage) {
        val x = bugCtrl.test
        super.start(stage)
    }
}
```

**Comment by edvin** [comment]
You need to call `super.start(stage)` first, since that will register the application and enable lookup of the default config path. Is that problematic for you to do? If so, I could look into making it available before.

**Comment by Finnerale** [comment]
I'm using the settings also to store the window's position and size.
If I set those props after `super.start(stage)` the window will apear first at the wrong position with the wrong size and then teleport and resize while visible which is quite annoying.

**Comment by edvin** [comment]
Would it work to do `override fun shouldShowPrimaryStage() = false` and then calling `stage.show()` after you adjusted the size in `start`?

**Comment by edvin** [comment]
Alternatively, maybe you could use the `config` property of your `App` class, which should be available all the time?

**Comment by Finnerale** [comment]
Your idea worked :+1:

**Comment by Finnerale** [comment]
`override fun shouldShowPrimaryStage() = false` and then calling `stage.show()` solved it

**Comment by edvin** [comment]
Great :))
