### ISSUE TITLE
Java 9 compatibility problems (bad use of reflection)

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#366]
The file Nodes.kt uses reflection to access private methods in the JavaFX framework, for example

        val resizer = skin.javaClass.getDeclaredMethod("resizeColumnToFitContent", TreeTableColumn::class.java, Int::class.java)
        resizer.isAccessible = true

these methods apparently habe been removed or moved with JDK-9 so that smartresize is now broken there and exceptions are raised:

```
Uncaught error
java.lang.NoSuchMethodException: javafx.scene.control.skin.TreeTableViewSkin.resizeColumnToFitContent(javafx.scene.control.TreeTableColumn, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
	at tornadofx.NodesKt$resizeColumnsToFitContent$doResize$2.invoke(Nodes.kt:309)
	at tornadofx.NodesKt$resizeColumnsToFitContent$doResize$2.invoke(Nodes.kt)
	at tornadofx.NodesKt.resizeColumnsToFitContent(Nodes.kt:314)
	at tornadofx.NodesKt.resizeColumnsToFitContent$default(Nodes.kt:307)
	at tornadofx.TreeTableSmartResize.call(SmartResize.kt:319)
	at tornadofx.TreeTableSmartResize.call(SmartResize.kt:286)
	at javafx.controls/javafx.scene.control.TreeTableView.setContentWidth(TreeTableView.java:1947)
	at javafx.controls/javafx.scene.control.TreeTableView.lambda$new$1(TreeTableView.java:400)
	at javafx.base/com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:327)
	at javafx.base/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.base/com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at javafx.base/com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.updateContentWidth(TableViewSkinBase.java:808)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.checkContentWidthState(TableViewSkinBase.java:567)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:490)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.controls/javafx.scene.control.TreeTableView.layoutChildren(TreeTableView.java:1513)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1773)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
```

**Comment by edvin** [comment]
There is nothing we can do about this before we create a JDK9 branch, as changing it would break JDK8 compatibility. There are a handful of cases just like this which we'll cover when we create the branch :)

**Comment by HaasJona** [comment]
Is it necessary to access private methods with reflection? These can obviously change all the time. I'm trying to use the JDK9 beta because of several JavaFX issues that haven't been backported.

**Comment by edvin** [comment]
Yes, the resizeColumnToFitContent method in the skin is private, so there is no other way AFAIK :(

**Comment by HaasJona** [comment]
The problem is this is just now forwards compatible. If I publish my application now and my users update to JDK9 in a few months when it's released, the app will stop working properly. If you must use private methods with reflection at least make sure to handle/ignore potential errors. Not smart resizing is bad but still much better than creating unhandled exception dialogs everywhere.

I'm wondering if it's possible to calculate the content width manually.

**Comment by edvin** [comment]
There are several other issues with JDK9 at the moment, so fixing this wouldn't really get us anywhere. Users won't be able to run TornadoFX against JDK9 before we release the first JDK9 compatible version I'm afraid. We be far behind the GA though :) A way to safe guard against issues with compatibility is simply to ship your app together with the JDK, so you control which version they run against. You can use FXLauncher, or at least package with javapackager manually if you don't want or need the automatic update functionality.

**Comment by HaasJona** [comment]
Is there a plan to start a JDK9 compatible branch? Remember that because of the Java 9 module system you aren't allowed (and aren't supposed to access) private methods in other modules, so features that you currently access with reflection will either need to be implemented with public methods instead or in the worst case removed.

**Comment by edvin** [comment]
I don't think I will have time personally before after Java One. If somebody wants to start the branch and begin the work that would be great :) 

The features that cannot be accessed with reflection could still be allowed to live there, but they would require a jvm parameter to work.

**Comment by edvin** [comment]
Closing this, as it has been addressed in the jdk9 branch. This might see another reimplementation before release though.
