### ISSUE TITLE
Giving a Controller class in SceneBuilder 8 causes javafx.fxml.LoadException: Controller value already specified.

### ISSUE THREAD

**Issue by hiucimon** [edvin/tornadofx#400]
I have this Program:

class PCGenMainApp : App(MainWindow::class, Styles::class)

class MainWindow:View("Game Table Application") {
    override val root: AnchorPane by fxml("/MainWindow.fxml")
}

class Styles : Stylesheet() {
    init {
        label {
            fontSize = 20.px
            fontWeight = FontWeight.BOLD
            backgroundColor += c("#cecece")
        }
    }
}

And it runs fine. If I specify a controller class in my SceneBuilder, it will not run, giving...

Aug 06, 2017 10:15:59 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
javafx.fxml.LoadException: Controller value already specified.
/Users/joe/PathfinderData/target/classes/MainWindow.fxml:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
	at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:914)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at tornadofx.UIComponent.loadFXML(Component.kt:829)
	at tornadofx.UIComponent$fxml$1.<init>(Component.kt:808)
	at tornadofx.UIComponent.fxml(Component.kt:807)
	at tornadofx.UIComponent.fxml$default(Component.kt:807)
	at org.hiucimon.MainWindow.<init>(PCGenMain.kt:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:401)
	at tornadofx.FXKt.find$default(FX.kt:387)
	at tornadofx.App.start(App.kt:79)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by edvin** [comment]
Short answer: You need to pass hasControllerAttribute=true to the fxml delegate function.

Long answer: https://github.com/edvin/tornadofx/issues/179

**Comment by hiucimon** [comment]
I added hasControllerAttribute=true , and a controller name of MainWindowController, and added:
class MainWindowController : Controller() {
}

and now I get

/Users/joe/PathfinderData/target/classes/MainWindow.fxml:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:922)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at tornadofx.UIComponent.loadFXML(Component.kt:829)
	at tornadofx.UIComponent$fxml$1.<init>(Component.kt:808)
	at tornadofx.UIComponent.fxml(Component.kt:807)
	at tornadofx.UIComponent.fxml$default(Component.kt:807)
	at org.hiucimon.MainWindow.<init>(PCGenMain.kt:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:401)
	at tornadofx.FXKt.find$default(FX.kt:387)
	at tornadofx.App.start(App.kt:79)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.ClassNotFoundException: MainWindowController
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:920)
	... 26 more

**Comment by edvin** [comment]
You need to supply a fully qualified package/class combo. Also, controllers should be a view, it wouldn't make sense to point it to a Controller instance.
