### ISSUE TITLE
Make field width more granular

### ISSUE THREAD

**Issue by sanchezmk** [edvin/tornadofx#407]
Currently all fields in a form share the same width. However when layouts are nested within a form this can be undesirable.
![image](https://user-images.githubusercontent.com/30213818/29252382-2f83e970-8066-11e7-857a-276a9c18a081.png)
Let's say that "Field r1b" and "Field r2b" in the last column had some longer text in them than the fields in the other 3 columns, this would cause all fields in all columns to become wider.

Can "Field r1b" and "Field r2b" be made to detect that they're within a vbox and share width only within their own vbox?

**Comment by edvin** [comment]
Can you post the code for this View? I'm sure we'll find a nice solution to this :)

**Comment by sanchezmk** [comment]
Here "Field 4a" was rightfully extended together with "Field 4b", but "Field 3a" and "Field 3b" should not have been extended:

![image](https://user-images.githubusercontent.com/30213818/29254606-23d9cc2a-8098-11e7-9ea1-62181f9d8c37.png)


```
package com.pt.tt.view

import javafx.scene.text.FontWeight
import tornadofx.*

class TestView : View("TestView") {

	override val root = vbox {

		form {
			label("Form1") { style(append = true) { fontSize = 2.em; fontWeight = FontWeight.BOLD } }
			hbox {
				fieldset("Fieldset1") {
					style(append = true) { padding = box(1.em) }
					field("Field1a") { textfield() }
					field("Field1b") { textfield() }
				}

				fieldset("Fieldset2") {
					style(append = true) { padding = box(1.em) }
					field("Field2a") { textfield() }
					field("Field2b") { textfield() }
				}
			}
		}

		form {
			label("Form2") { style(append = true) { fontSize = 2.em; fontWeight = FontWeight.BOLD } }
			hbox {
				fieldset("Fieldset3") {
					style(append = true) { padding = box(1.em) }
					field("Field3a") { textfield() }
					field("Field3b") { textfield() }
				}

				fieldset("Fieldset4") {
					style(append = true) { padding = box(1.em) }
					field("Field4a") { textfield() }
					field("Field4b (this field is longer)") { textfield() }
				}
			}
		}
	}
}
```

**Comment by genobis** [comment]
@sanchezmk: what stops you from making multiple forms? It's not a HTML and form is just a layout container made for the sole reason od keeping consistent label/field sizes. You want to have it consistent in the smaller scope? I believe more forms, one per column, is the answer here.

@edvin: I don't think it requires any changes on the framework's side. Probably possible, but it would introduce some ugly logic and you just can't predict any edge case anyway.

**Comment by QingMings** [comment]
This test code  in Tornadofx 1.7.12-SNAPSHOT  exception occurred ，and work fine in 1.7.11 .

```kotlin 
Oct 11, 2017 2:15:40 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.ClassCastException: javafx.scene.layout.HBox cannot be cast to tornadofx.Form
	at tornadofx.Fieldset.getForm(Forms.kt:340)
	at tornadofx.AbstractField.computePrefWidth(Forms.kt:287)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.HBox.getAreaWidths(HBox.java:457)
	at javafx.scene.layout.HBox.computeContentWidth(HBox.java:532)
	at javafx.scene.layout.HBox.computePrefWidth(HBox.java:425)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.Scene.getPreferredWidth(Scene.java:1697)
	at javafx.scene.Scene.resizeRootToPreferredSize(Scene.java:1673)
	at javafx.scene.Scene.preferredSize(Scene.java:1645)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at tornadofx.App.start(App.kt:94)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Oct 11, 2017 2:15:40 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.ClassCastException: javafx.scene.layout.HBox cannot be cast to tornadofx.Form
	at tornadofx.Fieldset.getForm(Forms.kt:340)
	at tornadofx.AbstractField.computePrefWidth(Forms.kt:287)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1997)
	at javafx.scene.layout.Region.computeMaxPrefAreaWidth(Region.java:1861)
	at javafx.scene.layout.VBox.computePrefWidth(VBox.java:409)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.HBox.getAreaWidths(HBox.java:457)
	at javafx.scene.layout.HBox.layoutChildren(HBox.java:627)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by edvin** [comment]
I believe this was fixed yesterday, can you try the latest snapshot?

**Comment by sanchezmk** [comment]
> @sanchezmk: what stops you from making multiple forms? It's not a HTML and form is just a layout container made for the sole reason od keeping consistent label/field sizes. You want to have it consistent in the smaller scope? I believe more forms, one per column, is the answer here.

Sorry I don't remember exactly why I couldn't use a separate form on each fieldset, I think it was something related to the sizing of some more complex controls I created, so I just created my own container templates and removed all forms from my project.

**Comment by edvin** [comment]
@sanchezmk If that's the case it sounds like you're not using any of the features provided by Form other than the default layout, so using a custom layout sounds like a reasonable solution. In any case, unless multiple forms proves not ideal, I think we have a solution to these situations, so no need to change anything in Form. Forms also supports arbitrary nested layout containers, so any layout should be achievable without much issue.

**Comment by Michael960** [comment]
> I think we have a solution to these situations

So what is the solution?
