### ISSUE TITLE
Stage.Style

### ISSUE THREAD

**Issue by vertexpipeline** [edvin/tornadofx#408]
I cannot change currentStage style via 
```kotlin
 currentStage?.initStyle(StageStyle.UNDECORATED)
````
in some View.
Log says that 
`java.lang.NullPointerException
	at tornadofx.UIComponent.getCurrentWindow(Component.kt:351)
	at tornadofx.UIComponent.getCurrentStage(Component.kt:480)
	at Views.View1.<init>(MainView.kt:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:401)
	at tornadofx.FXKt.find$default(FX.kt:387)
	at tornadofx.App.start(App.kt:79)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
`
 How can i solve it?
Generally, i try to disable window borders.

**Comment by edvin** [comment]
You're trying to access the stage in `init` perhaps, when the stage is not yet available. The stage is not assigned to the view at view construction time, but will be available in the `onDock` callback.

Also remember that you can't call `initStyle` on a stage that is already visible. This would be fine for the primary view, as `onDock` is actually called before show, but not in any arbitrary view assigned to that stage at a later time.

You can also override `start` in your `App` subclass, and init the stage there. If you do, remember to call `super` after you have configured the stage.

**Comment by vertexpipeline** [comment]
Thanks. It's a very informative response. I solved it.
