### ISSUE TITLE
Bug: unable to close InternalWindow due to unsafe type casting

### ISSUE THREAD

**Issue by genobis** [edvin/tornadofx#491]
Method `findParentOfType` (one of the important ones, I suppose) does not work correctly. In consequence, closing `InternalWindow` from within an embedded component is not possible (`close` method invoked directly for window instance works fine, the problem is with getting that instance). I have even written a test for this particular case and a following exception occurs:

```java
java.lang.RuntimeException: java.lang.ClassCastException: javafx.scene.layout.StackPane cannot be cast to tornadofx.InternalWindow

	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:161)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:269)
	at org.testfx.api.FxToolkit.setupFixture(FxToolkit.java:218)
	at tornadofx.tests.InternalWindowClosingTest.testClosing(InternalWindowClosingTest.kt:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: javafx.scene.layout.StackPane cannot be cast to tornadofx.InternalWindow
	at tornadofx.UIComponent.close(Component.kt:1049)
	at tornadofx.tests.InternalWindowClosingTest$testClosing$view$1.executeClose(InternalWindowClosingTest.kt:23)
	at tornadofx.tests.InternalWindowClosingTest$testClosing$1.run(InternalWindowClosingTest.kt:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$9(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

This bug doesn't affect current stable version, it was introduced in commit:
https://github.com/edvin/tornadofx/commit/19fcdf0e43439b9921c0d8dbaa95f57bb053a4d1

Most of it looks just fine to me and if not correct, at least logically equal to previous version (but it's very possible I'm missing something - in terms of Kotlin, a I am a very beginner). However, apparently `as?` safe cast isn't really that safe, when erasure comes into play.

As usual (if I can say that already ;) ), a fix is on the way.

**Comment by edvin** [comment]
@tieskedh Watch out for this when you refactor :) I wasn't aware of the issue myself though. Nice work spotting this @genobis !

**Comment by edvin** [comment]
Fixed by PR #492

**Comment by tieskedh** [comment]
@genobis @edvin thanks for mentioning!!!
Will add exception in styleguide.

**Comment by genobis** [comment]
@tieskedh once in a while we *will* encounter a caveat like that, and in many ways Kotlin is still an uncharted territory, at least for me ;)

A silly question - what is the style guide you are talking about? You mean the official one?

**Comment by tieskedh** [comment]
nope, it's not used  yet (that's why  you wasn't aware of it), but I am writing a [styleguide for tornadofx](https://gist.github.com/tieskedh/65a90173c867aca35e2b988ff4baabd1).
