### ISSUE TITLE
Run ok in IDE, package to Jar encounter issue "java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TableRowSkin"

### ISSUE THREAD

**Issue by ScottHuangZL** [edvin/tornadofx#503]
I try tornadofx recently. My sample run smoothly in the Idea IDE.
However, when I package it to single jar and run it, some view will show below error: 
**java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TableRowSkin**

Can you help on it? Thanks.

**The POM.xml**
...
` 
            <plugin>
                <artifactId> maven-assembly-plugin </artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>${main.class}</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>`
...

**The error msg:**

`java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TableRowSkin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at tornadofx.TableViewEditModel$enableDirtyTracking$1$1.createDefaultSkin(ItemControls.kt:887)
	at tornadofx.TableViewEditModel$enableDirtyTracking$1$1.createDefaultSkin(ItemControls.kt:886)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.applyCss(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
**Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.TableRowSkin**
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more

**Another error msg :**

java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TableRowSkin
	at tornadofx.TableViewEditModel$enableDirtyTracking$1$1.createDefaultSkin(ItemControls.kt:887)
	at tornadofx.TableViewEditModel$enableDirtyTracking$1$1.createDefaultSkin(ItemControls.kt:886)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.access$000(Unknown Source)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.access$400(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.access$3500(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:105)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

`

**Only below view been impacted, other view is ok.**
`package com.scotthuangzl.sample.view

import javafx.beans.property.SimpleIntegerProperty
import javafx.beans.property.SimpleStringProperty
import tornadofx.*

class MyTableViewEditModel : View("My View") {
    val controller: CustomerController by inject()
    var tableViewEditModel: TableViewEditModel<Customer> by singleAssign()
    override val root = borderpane {
        top = buttonbar {
            button("COMMIT").setOnAction {
                tableViewEditModel.commit()
            }
            button("ROLLBACK").setOnAction {
                tableViewEditModel.rollback()
            }
        }
        center = tableview<Customer> {
            items = controller.customers
            isEditable = true
            column("ID", Customer::idProperty)
            column("FIRST NAME", Customer::firstNameProperty).makeEditable()
            column("LAST NAME", Customer::lastNameProperty).makeEditable()
            enableCellEditing() //enables easier cell navigation/editing
            enableDirtyTracking() //flags cells that are dirty
            tableViewEditModel = editModel
        }
        bottom = hbox {
            button("Back to Main") {
                action {
                    replaceWith(MainView::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
                }
                shortcut("Ctrl+B")
            }
        }
    }
}

class CustomerController : Controller() {
    val customers = listOf(
            Customer(1, "Marley", "John"),
            Customer(2, "Schmidt", "Ally"),
            Customer(3, "Johnson", "Eric")
    ).observable()
}

class Customer(id: Int, lastName: String, firstName: String) {
    val lastNameProperty = SimpleStringProperty(this, "lastName", lastName)
    var lastName by lastNameProperty
    val firstNameProperty = SimpleStringProperty(this, "firstName", firstName)
    var firstName by firstNameProperty
    val idProperty = SimpleIntegerProperty(this, "id", id)
    var id by idProperty
}`

**Comment by edvin** [comment]
It looks like there is some issue with the runtime JRE. What version of Java are you running this against?

**Comment by ScottHuangZL** [comment]
I am using: jdk1.8.0_121
Thanks.

Btw, I also install JDK1.9, but I am sure I set JAVA_HOME to point to that 1.8 version.

**Comment by edvin** [comment]
Can you try to run it with the exact same JDK that you're running in IDEA? Since the `NoClassDefFoundError` occurs in `TableRowSkin` I can't see how this could be a TornadoFX issue. Maybe I lack imagination :)

**Comment by edvin** [comment]
I've seen several cases like this lately, they are all due to people running Java 9 when they thought they were running Java 8. That's the case here as well :)

**Comment by ScottHuangZL** [comment]
You are right, it is work after I uninstall the Java9 and only keep Java 8 in my computer.

But, could you advise how to avoid " people running Java 9 when they thought they were running Java 8"?  You know I have change the java home / path settings and so on.  Any other setting I need to adjust? Thanks.

**Comment by edvin** [comment]
There is nothing else to it than that, really :) A good check is always running `java -version` if you're in doubt.

**Comment by utzcoz** [comment]
@edvin I occur this problem when I use `tornadofx` with `OpenJDK 11` and `OpenJFX 11` in `Ubuntu 20.04`. In `Ubuntu 20.04`, it's not easy to install `OpenJFX 8`, and in `OpenJFX 11`, the `TableRowSkin` has moved to `javax.scene.control.skin` package. So I create a bridge class called `com.sun.javafx.scene.control.skin.TableRowSkin` in my project, and let it extends from `javax.scene.control.skin.TableRowSkin`.  And the demo from `tornadofx-guide` using `rowExpander` works correctly. Maybe community can create a bridge module to let `tornadofx` support `OpenJFX 11` and `OpenJFX 8` both. If the user likes me using `OpenJFX 11`, she/he can add the bridge module to its project dependency list to fix compatibility problem.

**Comment by edvin** [comment]
For TornadoFX 1.7 you must use JavaFX 8. For TornadoFX 2.0.0-SNAPSHOT you must use JDK13.
