### ISSUE TITLE
onUserSelect TableRow Bug

### ISSUE THREAD

**Issue by ryan-burmeister** [edvin/tornadofx#512]
I'm new to TornadoFX and love it with all my heart. I'm creating a todo application just to learn how everything works. When I run it in Idea, everything works fine and as expected, but when I build with Gradle and run the jar, I get some errors.

Specifically, the user should be able to double-click on a row in the table and that will make that item completed. Below is what happens when I run it from Idea.
![oct-25-2017 10-37-17-min](https://user-images.githubusercontent.com/12453590/32005373-21d77aea-b972-11e7-9c30-30753ea9c900.gif)

And this is what happens when I run the jar.
![oct-25-2017 10-50-17](https://user-images.githubusercontent.com/12453590/32005481-66053f0e-b972-11e7-8f26-c578bcafff13.gif)

I don't know how to simply create a jar that matches the Idea run, but I feel like there has to be some way. For purposes of this issue, I uploaded the project to git. It can be accessed here: https://github.com/ryan-burmeister/tornadofx-todos. And here is my MainView: https://github.com/ryan-burmeister/tornadofx-todos/blob/master/src/main/kotlin/com/ryanburmeister/todos/controller/MainView.kt.

I've tried to remove the "onUserSelect" starting on line 35, and that fixes the problem (obviously with the result of removing major functionality), so it has to be somewhere in there.

I'm running Java 1.8.0_131 (same version as in IntelliJ) on a MacBook Pro.

The full error message I get is below. Thanks.
```
Error in tornadofx.NodesKt.isInsideRow(Nodes.kt:564)

java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/TableColumnHeader
	at tornadofx.NodesKt.isInsideRow(Nodes.kt:564)
	at tornadofx.NodesKt$onUserSelect$isSelected$1.invoke(Nodes.kt:474)
	at tornadofx.NodesKt$onUserSelect$isSelected$1.invoke(Nodes.kt)
	at tornadofx.NodesKt$onUserSelect$1.handle(Nodes.kt:478)
	at tornadofx.NodesKt$onUserSelect$1.handle(Nodes.kt)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ClickGenerator.postProcess(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ClickGenerator.access$8300(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.TableColumnHeader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
```

**Comment by bekwam** [comment]
Hi,

I ran the JAR produced by your Gradle file on 1.8.0_121 and 1.8.0_152.  I don't have 131 handy.  I didn't get any errors.  I added items to the TextField, they displayed in the ListView, and were removed when I double-clicked.  I didn't see the stack trace referencing the com.sun classes.

I ran the JAR with a simple $ java -jar tornado_todos.jar command.

It sounds like this might be a JVM issue.  Can you try downloading and installing the latest JDK for the Mac and reproduce your error?  If it works, we can take a step back at why the 131 installation isn't working for you.

**Comment by ryan-burmeister** [comment]
@bekwam Hello bekwam.

Thanks for your reply. I ran the jar the same way you did through the command line and it worked as expected. I bundle my jars with [jar2app](https://github.com/Jorl17/jar2app#bundling-your-own-jdkjre). It has an option to bundle a certain JDK in with the application and I specified 1.8.151, and that worked as well. The app file didn't produce the error.

The error seems to only occur when I double click on the jar itself, or when I use jar2app without specifying a specific JDK. So it seems that the error occurs because my Mac thinks that my java version is JDK 9, which I have installed. But my JAVA_HOME is set to 1.8.152. So happily I'd like to note that **this is not a TornadoFX issue**. I was not able to replicate this in IDEA, however, so I don't know what the problem is exactly, but I know the solution.

Thanks a lot for the help. It's not a TorndadoFX issue, but if you have any idea how to make my Mac use JDK 1.8, I would appreciate the help, but I can figure that out on my own with time. Thanks again!

**Comment by bekwam** [comment]
No problem.  We'll be supporting Java 9 soon.  In the meantime, have you seen the FX Launcher project?  that might give you another option on how to run your app.

**Comment by ryan-burmeister** [comment]
I just check it out and saw "Combined with JavaFX native packaging", so I'm interested! I'll look into it. Thanks again for your help. I love this project and hope it grows!

**Comment by ryan-burmeister** [comment]
Last note: I used this https://gist.github.com/schnell18/bcb9833f725be22f6acd01f94b486392 to remove Java 9 and it fixed all my problems. It just uses JAVA_HOME.
