### ISSUE TITLE
Smart resize incompatible with optional column visibility

### ISSUE THREAD

**Issue by nihiluis** [edvin/tornadofx#564]
not sure if this is a bug.

when I use this
```kotlin
tableview {
...
                columnResizePolicy = SmartResize.POLICY
val mapCertainty = column(...)
                mapCertainty.setCellValueFactory { it.value.mapCategory }
                mapCertainty.visibleProperty().bindBidirectional(controller.mapVisibility)
}
```
and change the visibility via property I get this NPE

```
Dec 10, 2017 8:05:52 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt:402)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent(SmartResize.kt:410)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent$default(SmartResize.kt:397)
	at tornadofx.SmartResizeKt.resizeCall(SmartResize.kt:448)
	at tornadofx.SmartResize.call(SmartResize.kt:43)
	at tornadofx.SmartResize.call(SmartResize.kt:41)
	at javafx.scene.control.TableView.updateVisibleLeafColumns(TableView.java:1641)
	at javafx.scene.control.TableView.lambda$new$38(TableView.java:760)
	at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at com.sun.javafx.binding.BidirectionalBinding$BidirectionalBooleanBinding.changed(BidirectionalBinding.java:266)
	at com.sun.javafx.binding.BidirectionalBinding$BidirectionalBooleanBinding.changed(BidirectionalBinding.java:227)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at hi.MappingView$root$1$4$2$1.invoke(MappingView.kt:160)
	at hi.MappingView$root$1$4$2$1.invoke(MappingView.kt:42)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:513)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.scene.control.skin.TableViewSkin.resizeColumnToFitContent(TableViewSkin.java:257)
	... 76 more
```

**Comment by edvin** [comment]
Can you provide a complete View I can test?

By the way, you're not using the builders correctly, instead of assigning the column to a variable you should use the op block, .ie `column(..) { performOperationsHere() }`. You should also look into `cellFormat` instead of using `setCellValueFactory`.

**Comment by nihiluis** [comment]
thanks. I'll make one.

how do you mean builder? like this? cellFactory, cellValueFactory and visibleProperty are broken in some way now. just doesnt have the previous effect.

```kotlin
                column<SomeModel, MapCategory>("Map Certainty", SomeModel::mapCategory) {
                    cellFactory = Callback {
                        val cb = ChoiceBoxTableCell<SomeModel, MapCategory>()
                        cb.items.addAll(MapCategory.values())

                        return@Callback cb
                    }
                    cellValueFactory = Callback {
                        it.value.mapCategory
                    }
                }.cellFormat {
                    visibleProperty().bindBidirectional(controller.mapVisibility)
                }
```

**Comment by edvin** [comment]
They are not broken :) Post something that compiles and exhibits the issue and I’ll investigate + clean up your code :)

**Comment by nihiluis** [comment]
```
class TestModel : ViewModel() {
    val x = bind { SimpleStringProperty("hi") }
    val y = bind { SimpleStringProperty("hallo") }
    val z = bind { SimpleStringProperty("hola") }
}

class TestView : View() {
    val visibility = SimpleBooleanProperty(false)

    override val root = vbox {
        tableview<TestModel> {
            items = listOf(TestModel(), TestModel(), TestModel()).observable()

            column("X", TestModel::x)
            column<TestModel, String>("Y", TestModel::y) {
                onDoubleClick {
                    visibility.set(true)
                }
            }
            column<TestModel, String>("Z", TestModel::z) {
                setCellFactory {
                    val tc = TextFieldTableCell<TestModel, String>(DefaultStringConverter())
                    tc.onMouseClicked = EventHandler {
                        tc.startEdit()
                    }

                    return@setCellFactory tc
                }
            }.cellFormat {
                visibleProperty().bindBidirectional(visibility)
            }

            enableCellEditing()
        }

        tableview<TestModel> {
            items = listOf(TestModel(), TestModel(), TestModel()).observable()

            column("X", TestModel::x)
            column("Y", TestModel::y).apply {
                onDoubleClick {
                    visibility.set(true)
                }
            }
            column<TestModel, String>("Z", TestModel::z).apply {
                setCellFactory({
                    val tc = TextFieldTableCell<TestModel, String>(DefaultStringConverter())
                    tc.onMouseClicked = EventHandler {
                        tc.startEdit()
                    }

                    return@setCellFactory tc
                })

                cellValueFactory = Callback {
                    it.value.z
                }

                visibleProperty().bindBidirectional(visibility)

                // decomment this to get exception, the original issue
                //columnResizePolicy = SmartResize.POLICY
            }

            enableCellEditing()
        }
    }
}
```

**Comment by nihiluis** [comment]
column z is only hidden properly in table2, if you move the contents of cellFormat to the {} it works properly as well in {}. my mistake.

decommenting columnResizePolicy should result in the error of the original issue
