### ISSUE TITLE
ObservableList in an FXProperties class, and consume resources with Retrofit

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#577]
Hello, I am trying to write my class "Client" with FXProperties, but I have an attribute that is a list, and I can not declare it like the others:
```
class Client {

    val idProperty = SimpleIntegerProperty()
    var id by idProperty

    val nombreProperty = SimpleStringProperty()
    var nombre by nombreProperty

    val emailListProperty = FXCollections.observableArrayList<Email>()
    var emailList by listaContraindicacionesProperty // error

}
```
This is the error message that comes out:
```
Missing 'getValue ...
Missing 'setValue ...
```
So the way I solve it is the following, I do not know if it is the correct way:
```
val emailListProperty = FXCollections.observableArrayList<Email>()
var emailList by listaContraindicacionesProperty.toProperty() // I execute the method to the property ()
```
But when it comes to consuming a REST API with Retrofit, I have an error with the ObservableList:

`Can not find a deserializer for non-concrete Collection type [collection type; class javafx.collections.ObservableList, contains [simple type, class com.clario.ClarioDesktopApp.bean.entity.Email]]`

Any idea how to fix it ? Maybe I do not have to see at all with TornadoFx, but I would like to solve this problem. Thank you

**Comment by edvin** [comment]
If you want to wrap your list in a property, use the `SimpleListProperty` construct:

```kotlin
val emailListProperty = SimpleListProperty<Email>()
var emailList by emailListProperty
```

**Comment by TioCoding** [comment]
Thank you, that solves my first problem, but know how I could solve this exception?
(The problem comes out when trying to deserialize an ObservableList)
```
Caused by: java.lang.IllegalArgumentException: Can not find a deserializer for non-concrete Collection type [collection type; class javafx.collections.ObservableList, contains [simple type, class com.clario.ClarioDesktopApp.bean.entity.Email]]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:1021)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:391)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 38 more
```

**Comment by edvin** [comment]
I think how to deserialize an ObservableList using Jackson falls outside the scope of TornadoFX  :)
