### ISSUE TITLE
using DateTimePacker from tornadofx controllers

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#613]
hello
i try to use tornadofx controllers  
the DateTimePacker didn't work with me
what is wrong in this code
```
field("time") {
                    this+=DateTimePicker().apply {
                        dateTimeValueProperty().bind(model.date)
                    }
                }
```

**Comment by edvin** [comment]
First of all, you're not saying what happens - "didn't work" really isn't an error description :) Please include a complete runnable sample and describe the problem.

**Comment by mostfa-ayad** [comment]
you are right , this is my fault  
i will close this issue and open new descripe my problem

**Comment by edvin** [comment]
Thanks - but you can keep the issue, just describe the error better and we'll figure it out :)

**Comment by mostfa-ayad** [comment]
ok
this is the error
```
java.lang.RuntimeException: A bound value cannot be set.
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:142)
	at tornadofx.control.DateTimePicker.lambda$new$0(DateTimePicker.java:46)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.control.ComboBoxBase.setValue(ComboBoxBase.java:150)
	at com.sun.javafx.scene.control.skin.DatePickerContent.selectDayCell(DatePickerContent.java:689)
	at com.sun.javafx.scene.control.skin.DatePickerContent.lambda$createDayCells$174(DatePickerContent.java:731)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```
i bind the picker to LocalDateTime 
```
field("time") {
                    this+=DateTimePicker().apply {
                        dateTimeValueProperty().bind(model.date)
                    }
                }
```
error is excute

**Comment by edvin** [comment]
Can you post a complete sample app please? :)

**Comment by mostfa-ayad** [comment]
[test.zip](https://github.com/edvin/tornadofx/files/1675084/test.zip)

**Comment by edvin** [comment]
The problem is that you made a unidirectional binding against the `dateTimeValueProperty`, effectively blocking the UI component from updating the value. You need to bind using a bidirectional binding instead, so simply change the binding to:

```kotlin
dateTimeValueProperty().bindBidirectional(model.date)
```

**Comment by mostfa-ayad** [comment]
thank you :)

**Comment by edvin** [comment]
You're welcome. Nice to get this documented :)
