### ISSUE TITLE
[Help]  Error occurred when shut down the Application

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#669]
```kotlin

import javafx.geometry.Point2D
import javafx.scene.Node
import org.controlsfx.control.PopOver
import tornadofx.*

class SearchView : View("My View") {
    lateinit var popOver:PopOver

    override val root = borderpane {

        center {
            textfield {
                focusedProperty().addListener { _, _, focused ->
                    if (focused) {
                        println("focused")
                        if (!::popOver.isInitialized){
                            popOver = createPopOver()
                            val point =calulateNodeLocation(this)
                            popOver.show(this,point.x,point.y)
                        }else{
                            val point =calulateNodeLocation(this)
                            popOver.show(this,point.x,point.y)
                        }
                    }else{
                        println("Unfocused")
                    }
                }
            }
        }
        prefWidth=500.0
        prefHeight=500.0
    }



    fun  createPopOver():PopOver{
        val popOver = PopOver()
        popOver.isDetachable=false
        popOver.isDetached=false
        popOver.arrowSize=6.0
        popOver.arrowIndent=17.0
        popOver.arrowLocation= PopOver.ArrowLocation.TOP_CENTER
        popOver.cornerRadius=6.0
        popOver.isHeaderAlwaysVisible=false
        popOver.isAnimated=true
        popOver.isCloseButtonEnabled=true
        return popOver
    }

    fun calulateNodeLocation(node: Node):Point2D{
        val bounds =node.boundsInLocal
        val screenBounds=node.localToScreen(bounds)
        val x = screenBounds.minX
        val y = screenBounds.maxY
        val width = screenBounds.width

        return Point2D(x+width/2,y)
    }

    override fun onUndock() {
        if (::popOver.isInitialized) {
            popOver.hide()

        }
    }


}

```
I try to when text box gains focus pop up a pop-up box，
When the pop-up box pops up, close the application, error occurs

<details><summary>Exception details </summary>
<p>

```java
Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.GlassScene.getClearColor(GlassScene.java:339)
	at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:100)
	at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:282)
	at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:143)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2424)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.GlassScene.getClearColor(GlassScene.java:339)
	at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:100)
	at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:282)
	at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:143)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2424)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
信息: Detected cycle handling error, aborting.
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:52 PM tornadofx.DefaultErrorHandler uncaughtException
信息: Detected cycle handling error, aborting.
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.IllegalStateException: The window has already been closed
	at com.sun.glass.ui.Window.checkNotClosed(Window.java:307)
	at com.sun.glass.ui.Window.getNativeWindow(Window.java:337)
	at com.sun.prism.PresentableState.update(PresentableState.java:350)
	at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:103)
	at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:282)
	at com.sun.javafx.tk.quantum.WindowStage.lambda$setScene$389(WindowStage.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithRenderLock(QuantumToolkit.java:407)
	at com.sun.javafx.tk.quantum.WindowStage.setScene(WindowStage.java:260)
	at javafx.stage.Window$9.invalidated(Window.java:878)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.hide(Window.java:947)
	at javafx.stage.PopupWindow.hide(PopupWindow.java:468)
	at org.controlsfx.control.PopOver.lambda$hide$5(PopOver.java:530)
	at javafx.animation.Animation.impl_finished(Animation.java:1132)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.IllegalStateException: The window has already been closed
	at com.sun.glass.ui.Window.checkNotClosed(Window.java:307)
	at com.sun.glass.ui.Window.getNativeWindow(Window.java:337)
	at com.sun.prism.PresentableState.update(PresentableState.java:350)
	at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:103)
	at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:282)
	at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:143)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2424)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
信息: Detected cycle handling error, aborting.
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Mar 14, 2018 5:42:53 PM tornadofx.DefaultErrorHandler uncaughtException
信息: Detected cycle handling error, aborting.
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setPlatformEnabled(WindowStage.java:840)
	at com.sun.javafx.tk.quantum.GlassStage.windowsSetEnabled(GlassStage.java:171)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:517)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at tornadofx.DefaultErrorHandler.showErrorDialog(ErrorHandler.kt:122)
	at tornadofx.DefaultErrorHandler.access$showErrorDialog(ErrorHandler.kt:15)
	at tornadofx.DefaultErrorHandler$uncaughtException$1.run(ErrorHandler.kt:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

```

**Comment by edvin** [comment]
This is not a TornadoFX bug. Try it with a plain JavaFX project written in Kotlin and with ControlsFX on the classpath. You will get the same error, but somewhat different stack trace, since it won't be picked up by TornadoFX's error handler.
