### ISSUE TITLE
Support for :not(s) css pseudoclass

### ISSUE THREAD

**Issue by ethanmdavidson** [edvin/tornadofx#694]
I'm trying to style a tableView so that rows with certain properties will have a different background color. I have been able to accomplish this by adding a cssclass to the desired rows. However, this overrides the default styling for :selected. My first intuition was to use `not(selected)` (sort of like `and(selected)`) but this doesn't exist. Next I tried wrapping it in `and(":not(:selected)"){` but I get an exception:
```
Apr 04, 2018 11:52:28 AM tornadofx.CssSelectionBlock <init>
WARNING: CSS rule caused an error
java.lang.IllegalArgumentException: Invalid CSS Rule Set: :not(:selected)
	at tornadofx.CSSKt.toRuleSet(CSS.kt:1184)
	at tornadofx.CSSKt.toSelector(CSS.kt:1178)
	at tornadofx.CssSelectionBlock.and(CSS.kt:946)
```
Which makes sense, because looking at the JavaFX CSS Reference, it appears that the [negation pseudoclass](http://www.w3.org/TR/selectors-3/#negation) isn't supported.

Is there a work around to invert the pseudoclass selection, or a better way to achieve this functionality?

**Comment by ethanmdavidson** [comment]
I just figured out that I can achieve what I want by using `unsafe("-fx-control-inner-background", myColor)`.
