### ISSUE TITLE
TestFX and parameters NPE

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#774]
When creating a test with ApplicationTest as shown in #500 the test crashes with an IllegalStateException:

```
java.lang.IllegalStateException: parameters must not be null
	at tornadofx.App.detectDiContainerArgument(App.kt:107)
	at tornadofx.App.start(App.kt:74)
	at tornadofx.testapps.TestFxTest.start(TestFxTest.kt:25)
	at org.testfx.framework.junit.ApplicationAdapter.start(ApplicationAdapter.java:54)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$61(ApplicationServiceImpl.java:62)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$9(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	... 1 more
```

This occurs since v1.7.16

Is there a way to run tests on my complete application or can they only be run on single views?

**Comment by dominiks** [comment]
Yes latest snapshot opens the app as expected. Thanks for your quick response!
