### ISSUE TITLE
Kotlin-reflect 1.3.0 and TornadoFX 1.7.18 exception

### ISSUE THREAD

**Issue by ValV** [edvin/tornadofx#842]
```
java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at tornadofx.NodesKt.findParentOfType(Nodes.kt:1035)
	at tornadofx.UIComponent.close(Component.kt:1334)
	at tornadofx.Wizard.cancel(Wizard.kt:81)
	at tornadofx.Wizard.onCancel(Wizard.kt:77)
	at com.github.valv.demo.tfx.WizardDemo$WizardDemo.onCancel(WizardDemo.kt:15)
	at tornadofx.Wizard$root$1$4$1$3$1.invoke(Wizard.kt:174)
	at tornadofx.Wizard$root$1$4$1$3$1.invoke(Wizard.kt:23)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:406)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
```
This exception occurs for me, when I click `Cancel` button in `Wizard`. It can be solved within _IntelliJ IDEA_ IDE, but not when I run my project jars with the following in the `classpath`:
```
annotations-13.0.jar
kotlin-reflect-1.3.0.jar
kotlin-stdlib-1.3.0.jar
kotlin-stdlib-common-1.3.0.jar
tornadofx-1.7.18-SNAPSHOT.jar
```
The exception rises again.
Possible solution for IDE: explicitly add `kotlin-reflect` to the dependencies for a build system templates (_Maven_, _Gradle_), when `1.7.18` is out.
With `1.7.17` this does not happen

**Comment by Aqluse** [comment]
Seems like I'm getting same (I think so) error for my custom scroll pane class from Java
```
java.lang.reflect.InvocationTargetException
	at com.aqlusesoftware.musictool.app.CustomErrorHandler.uncaughtException(Main.kt:70)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/aqlusesoftware/musictool/view/SmoothishScrollpane
	at com.aqlusesoftware.musictool.view.CustomComponentsKt.smoothScrollpane(CustomComponents.kt:41)
	at com.aqlusesoftware.musictool.view.CustomComponentsKt.smoothScrollpane$default(CustomComponents.kt:40)
	at com.aqlusesoftware.musictool.view.MainView.<init>(MainView.kt:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:402)
	at tornadofx.FXKt.find$default(FX.kt:388)
	at tornadofx.App.start(App.kt:78)
	at com.aqlusesoftware.musictool.app.Main.start(Main.kt:28)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.aqlusesoftware.musictool.view.SmoothishScrollpane
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

**Comment by edvin** [comment]
Do any of you have a small sample app I can play with to investigate this?

**Comment by Aqluse** [comment]
I can provide whole project, it isn't very big, but not small one

**Comment by edvin** [comment]
I would prefer a minimal sample which exhibits the issue so I can be sure I'm debugging the right thing :) Perhaps just make a copy and remove superfluous code?

**Comment by Aqluse** [comment]
Okay, I try, but it will take some more time, I could provide you full app in moment

**Comment by Aqluse** [comment]
[ClassNotFoundIssueTornadoFX.zip](https://github.com/edvin/tornadofx/files/2788976/ClassNotFoundIssueTornadoFX.zip)

There it is

**Comment by edvin** [comment]
This is in no way a minimal sample app. It's riddled with dependencies and atypical configuration. There could be a number of issues here not directly related to TornadoFX even. I will investigate if you can provide a minimal sample app, but I don't have time to wade through this, sorry :)

**Comment by Aqluse** [comment]
What do you mean by atypical configuration?

**Comment by edvin** [comment]
It differs substantially from the template we use at least. If you can cut it down to the bare minimum and remove unneeded plugins and dependencies in the build file so I know that I'm in fact investigating a TornadoFX I'd be happy to look at it :)

**Comment by Aqluse** [comment]
[ClassNotFoundIssueTornadoFX.zip](https://github.com/edvin/tornadofx/files/2793111/ClassNotFoundIssueTornadoFX.zip)
I hope now it's ok

**Comment by edvin** [comment]
Great, that made it a lot easier to figure out. The problem is that you have not configured your project correctly for mixing Java and Kotlin classes. `SmoothishScrollpane.java` is placed under `src/main/kotlin` and will not be compiled by default. Move it to `src/main/java` and the corresponding package structure, and it works with no other changes to your project.

**Comment by Aqluse** [comment]
@edvin So seems like maybe OP have a bit another issue, I just had almost same mentioned dependencies

**Comment by edvin** [comment]
Sweet. At least now this is searchable for others if they get into the same situation :)
