### ISSUE TITLE
stage title can't be changed.

### ISSUE THREAD

**Issue by MairwunNx** [edvin/tornadofx#972]
On JavaFx, changing the stage title is fine, with TornadoFx I get an exception. I understand that I can change the name through the view arguments, but I need to change it dynamically from a library that is simultaneously compatible with JavaFx and TornadoFx.

But I have a problem with changing the stage title.
It also can't be changed with kotlin code.

How i change stage title:
```
            try {
                windowOptionsInstance.stage.title = text
            } catch (runtimeException: RuntimeException) {
                Logger.getLogger(TitlePart::class.java.name).log(
                    Level.SEVERE,
                    "Failed to set new title value for stage. Sorry. This is usually discarded when using TornadoFx."
                )
            }
```

If i remove try-catch block with suppressing exception - i get runtime exception
```
Exception in Application start method
Apr 23, 2019 7:52:02 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Stage.title : A bound value cannot be set.
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:140)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.stage.Stage.setTitle(Stage.java:722)
	at jfxwindow.parts.TitlePart.setTitleText(TitlePart.kt:59)
	at jfxwindow.parts.TitlePart.applyTitleProperties$jfx_window(TitlePart.kt:21)
	at jfxwindow.base.Window.callInitMethods(Window.kt:566)
	at jfxwindow.base.Window.create(Window.kt:486)
	at com.mairwunnx.kdemo.Application.start(Application.kt:42)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	... 1 more  
```

**Comment by edvin** [comment]
You can call `unbind()` in the `titleProperty` and manage it yourself if you want to :)

**Comment by MairwunNx** [comment]
@edvin Thanks, it fully fix my problem. Solved. 😉🎉
