### ISSUE TITLE
MenuBar ContextMenu is null

### ISSUE THREAD

**Issue by Mosch0512** [edvin/tornadofx#975]
So i am not sure if this is the fault of tornadoFx.

If i am creating an menubar with an menu and i want to prevent closing the menu when loosing focus(``` contextMenu.autoHideProperty().set(false) ```) i tryed to do sth like that.

**I want to do that for beeing able to check the SubWindow with SecenicView**

but it tells me that contextMenu is null.
does this make sense?

```kotlin
class TestApp : App(TestView::class)

class TestView : View() {
    override val root = anchorpane {
        menubar {
            menu("menu") {
                item("item")
                contextMenu.autoHideProperty().set(false) // ContextMenu is null?
            }
        }
    }
}
```

when running:
```java
java.lang.NullPointerException
	at com.test.app.TestView$root$1$1$1.invoke(TestApp.kt:12)
	at com.test.app.TestView$root$1$1$1.invoke(TestApp.kt:7)
	at tornadofx.MenuKt.menu(Menu.kt:26)
	at tornadofx.MenuKt.menu$default(Menu.kt:25)
	at com.test.app.TestView$root$1$1.invoke(TestApp.kt:10)
	at com.test.app.TestView$root$1$1.invoke(TestApp.kt:7)
	at tornadofx.ControlsKt.menubar(Controls.kt:944)
	at com.test.app.TestView$root$1.invoke(TestApp.kt:9)
	at com.test.app.TestView$root$1.invoke(TestApp.kt:7)
	at tornadofx.LayoutsKt.anchorpane(Layouts.kt:514)
	at com.test.app.TestView.<init>(TestApp.kt:8)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:417)
	at tornadofx.FXKt.find$default(FX.kt:406)
	at tornadofx.App.start(App.kt:81)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$166(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by edvin** [comment]
You are calling `Control.getContextMenu()` when you write `contextMenu.`, so since you haven't defined a context menu, that getter returns null. We do have a `contextmenu` builder you can use to create a context menu.

**Comment by Mosch0512** [comment]
So this means i have to replace my menubar/menus with contextmenus? I cant do something similar with menu?

**Comment by edvin** [comment]
I'm not sure there is an API in JavaFX to control what happens to an already open menu when the window looses focus, so you might need to create your own control if this is important to you. Either that, or look at the source code for the Menu element in JavaFX to investigate if you can control this behavior somehow :)

**Comment by Mosch0512** [comment]
Hmm i kind of expected that answer :D ^^.

Okay thx a lot :)

So i have three options now:
- Check JavaFx code for options
- Implementing my own control

Hmm i will update this issue once i found sth(if i xD)

**Comment by Mosch0512** [comment]
I am going to implement my own control :D xD
