### ISSUE TITLE
IndexOutOfBoundsException for CustomWizard : Wizard

### ISSUE THREAD

**Issue by Mosch0512** [edvin/tornadofx#992]
I tried to implement my own **CustomWizard** where the steps are displayed at the top from left to right. And as base i wanted to use the Wizard.

Here my CustomWizard it equals Wizard but left is removed and top is changed.
```kotlin
abstract class CustomWizard @JvmOverloads constructor(title: String? = null, heading: String? = null) : Wizard(title) {
        override val root = borderpane {
        addClass(WizardStyles.wizard)
        top {
            vbox {
                hbox(5) {
                    bindChildren(pages) { page ->
                        val isPageActive = currentPageProperty.isEqualTo(page)

                        hyperlink("") {
                            textProperty().bind(stringBinding(numberedStepsProperty) { "${if (numberedSteps) (pages.indexOf(page)).toString() + ". " else ""}${page.title}" })
                            toggleClass(WizardStyles.bold, isPageActive)
                            action {
                                if (stepLinksCommits && pages.indexOf(page) > pages.indexOf(currentPage)) {
                                    currentPage.onSave()
                                    if (currentPage.isComplete) currentPage = page
                                } else {
                                    currentPage = page
                                }
                            }
                            enableWhen { enableStepLinksProperty }
                        }
                    }
                }
            }
        }
        center {
            stackpane {
                addClass(WizardStyles.content)
                bindChildren(pages) { page ->
                    val isPageActive = currentPageProperty.isEqualTo(page)
                    page.root.apply {
                        visibleWhen { isPageActive }
                    }
                }
            }
        }
        bottom {
            buttonbar {
                addClass(WizardStyles.buttons)
                button(type = ButtonBar.ButtonData.BACK_PREVIOUS) {
                    textProperty().bind(backButtonTextProperty)
                    runLater {
                        enableWhen(canGoBack)
                    }
                    action { back() }
                }
                button(type = ButtonBar.ButtonData.NEXT_FORWARD) {
                    textProperty().bind(nextButtonTextProperty)
                    runLater {
                        enableWhen(canGoNext.and(hasNext))
                    }
                    action { next() }
                }
                button(type = ButtonBar.ButtonData.CANCEL_CLOSE) {
                    textProperty().bind(cancelButtonTextProperty)
                    action { onCancel() }
                }
                button(type = ButtonBar.ButtonData.FINISH) {
                    textProperty().bind(finishButtonTextProperty)
                    runLater {
                        enableWhen(canFinish)
                    }
                    action {
                        currentPage.onSave()
                        if (currentPage.isComplete) {
                            onSave()
                            if (isComplete) close()
                        }
                    }
                }
            }
        }
    }
}
```

But when i am using that i am getting an **IndexOutOfBoundsException** if i add more than two stepts.

```kotlin
class MyCustomWizard: CustomWizard() {
    init {
        add(ViewOne::class)
        add(ViewTwo::class)
    }
}

class ViewOne : View("View One") {
    override val root = borderpane {
        button("My Button View One") {  }
    }
}
class ViewTwo : View("View Two") {
    override val root = borderpane {
        button("My Button View Two") {  }
    }
}
```

```java
tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.AbstractList.rangeCheckForAdd(AbstractList.java:605)
	at java.util.AbstractList.addAll(AbstractList.java:257)
	at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:110)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:252)
	at tornadofx.ListConversionListener.onChanged(Collections.kt:463)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at tornadofx.FXKt.addChildIfPossible(FX.kt:538)
	at tornadofx.FXKt.addChildIfPossible$default(FX.kt:498)
	at tornadofx.NodesKt.plusAssign(Nodes.kt:189)
	at tornadofx.UIComponent.add(Component.kt:887)
	at tornadofx.UIComponent.add$default(Component.kt:885)
	at com.test.systems.goapp.views.wizard.update.MyCustomWizard.<init>(MyCustomWizard.kt:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:436)
	at tornadofx.FXKt.find$default(FX.kt:425)
	at tornadofx.UIComponent.replaceWith(Component.kt:1202)
	at tornadofx.UIComponent.replaceWith$default(Component.kt:1201)
	at com.test.systems.goapp.views.MainContentView$root$1$2.handle(MainContentView.kt:23)
	at com.test.systems.goapp.views.MainContentView$root$1$2.handle(MainContentView.kt:9)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$358(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by edvin** [comment]
There is functionality in the Wizard that relies on the components it lays out, so you should not override the root property and all the children of it. Instead, manipulate what is there, or create your own component :) This might work:

```kotlin
abstract class CustomWizard @JvmOverloads constructor(title: String? = null, heading: String? = null) : Wizard(title) {
    init {
        with(root) {
            // Clear the left container
            left = null
            // Build breadcrumbs at the top
            top {
                vbox {
                    hbox(5) {
                        bindChildren(pages) { page ->
                            val isPageActive = currentPageProperty.isEqualTo(page)

                            hyperlink("") {
                                textProperty().bind(stringBinding(numberedStepsProperty) { "${if (numberedSteps) (pages.indexOf(page)).toString() + ". " else ""}${page.title}" })
                                toggleClass(WizardStyles.bold, isPageActive)
                                action {
                                    if (stepLinksCommits && pages.indexOf(page) > pages.indexOf(currentPage)) {
                                        currentPage.onSave()
                                        if (currentPage.isComplete) currentPage = page
                                    } else {
                                        currentPage = page
                                    }
                                }
                                enableWhen { enableStepLinksProperty }
                            }
                        }
                    }
                }
            }
        }

    }
}
```

**Comment by Mosch0512** [comment]
You are amazing this works :D

Just one more thing what do you mean here with creating my one one? Like without using the Wizard of TornadoFx?

**Comment by edvin** [comment]
Haha, great :) What I meant was that your implementation repeated most of the code in Wizard, so you might as well have created a component that wasn't a subclass of Wizard. Since your actual changes represents very little code, I think the current approach is better though.

**Comment by Mosch0512** [comment]
Yeah thx a lot I will try to participate at TornadoFx in the near future :D Love it great framework :D

**Comment by edvin** [comment]
Thank you :))
